/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 47
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__newline = 1,
  anon_sym_COLON = 2,
  anon_sym_DOTl = 3,
  anon_sym_COMMA = 4,
  sym_directive_name = 5,
  sym_register = 6,
  anon_sym_POUND = 7,
  anon_sym_DOTb = 8,
  anon_sym_DOTf = 9,
  anon_sym_EQ = 10,
  anon_sym_PLUS = 11,
  anon_sym_DASH = 12,
  sym_number = 13,
  sym_char = 14,
  sym_string = 15,
  sym_alias = 16,
  anon_sym_BANGINCLUDE = 17,
  aux_sym_path_token1 = 18,
  anon_sym_BANGDEFINE = 19,
  sym_identifier = 20,
  sym_comment = 21,
  sym_source_file = 22,
  sym__line = 23,
  sym_label = 24,
  sym_local_label = 25,
  sym__statement = 26,
  sym_instruction = 27,
  sym_directive = 28,
  sym__operand = 29,
  sym__argument = 30,
  sym_immediate = 31,
  sym_label_ref = 32,
  sym_preproc_include = 33,
  sym_path = 34,
  sym_preproc_define = 35,
  sym_define_value = 36,
  aux_sym_source_file_repeat1 = 37,
  aux_sym__line_repeat1 = 38,
  aux_sym_instruction_repeat1 = 39,
  aux_sym_directive_repeat1 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__newline] = "_newline",
  [anon_sym_COLON] = ":",
  [anon_sym_DOTl] = ".l",
  [anon_sym_COMMA] = ",",
  [sym_directive_name] = "directive_name",
  [sym_register] = "register",
  [anon_sym_POUND] = "#",
  [anon_sym_DOTb] = ".b",
  [anon_sym_DOTf] = ".f",
  [anon_sym_EQ] = "=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [sym_number] = "number",
  [sym_char] = "char",
  [sym_string] = "string",
  [sym_alias] = "alias",
  [anon_sym_BANGINCLUDE] = "!INCLUDE",
  [aux_sym_path_token1] = "path_token1",
  [anon_sym_BANGDEFINE] = "!DEFINE",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_label] = "label",
  [sym_local_label] = "local_label",
  [sym__statement] = "_statement",
  [sym_instruction] = "instruction",
  [sym_directive] = "directive",
  [sym__operand] = "_operand",
  [sym__argument] = "_argument",
  [sym_immediate] = "immediate",
  [sym_label_ref] = "label_ref",
  [sym_preproc_include] = "preproc_include",
  [sym_path] = "path",
  [sym_preproc_define] = "preproc_define",
  [sym_define_value] = "define_value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__line_repeat1] = "_line_repeat1",
  [aux_sym_instruction_repeat1] = "instruction_repeat1",
  [aux_sym_directive_repeat1] = "directive_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__newline] = sym__newline,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOTl] = anon_sym_DOTl,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_directive_name] = sym_directive_name,
  [sym_register] = sym_register,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_DOTb] = anon_sym_DOTb,
  [anon_sym_DOTf] = anon_sym_DOTf,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_number] = sym_number,
  [sym_char] = sym_char,
  [sym_string] = sym_string,
  [sym_alias] = sym_alias,
  [anon_sym_BANGINCLUDE] = anon_sym_BANGINCLUDE,
  [aux_sym_path_token1] = aux_sym_path_token1,
  [anon_sym_BANGDEFINE] = anon_sym_BANGDEFINE,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_label] = sym_label,
  [sym_local_label] = sym_local_label,
  [sym__statement] = sym__statement,
  [sym_instruction] = sym_instruction,
  [sym_directive] = sym_directive,
  [sym__operand] = sym__operand,
  [sym__argument] = sym__argument,
  [sym_immediate] = sym_immediate,
  [sym_label_ref] = sym_label_ref,
  [sym_preproc_include] = sym_preproc_include,
  [sym_path] = sym_path,
  [sym_preproc_define] = sym_preproc_define,
  [sym_define_value] = sym_define_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__line_repeat1] = aux_sym__line_repeat1,
  [aux_sym_instruction_repeat1] = aux_sym_instruction_repeat1,
  [aux_sym_directive_repeat1] = aux_sym_directive_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOTl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_directive_name] = {
    .visible = true,
    .named = true,
  },
  [sym_register] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOTb] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOTf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BANGINCLUDE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_path_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BANGDEFINE] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_local_label] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym__operand] = {
    .visible = false,
    .named = true,
  },
  [sym__argument] = {
    .visible = false,
    .named = true,
  },
  [sym_immediate] = {
    .visible = true,
    .named = true,
  },
  [sym_label_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_include] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_define] = {
    .visible = true,
    .named = true,
  },
  [sym_define_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_instruction_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_direction = 1,
  field_mnemonic = 2,
  field_name = 3,
  field_path = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_direction] = "direction",
  [field_mnemonic] = "mnemonic",
  [field_name] = "name",
  [field_path] = "path",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_mnemonic, 0},
  [2] =
    {field_path, 1},
  [3] =
    {field_name, 1},
  [4] =
    {field_name, 1},
    {field_value, 2},
  [6] =
    {field_direction, 0},
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '\n', 31,
        '\r', 1,
        '!', 7,
        '"', 2,
        '#', 42,
        '\'', 18,
        '+', 48,
        ',', 34,
        '-', 49,
        '.', 19,
        ':', 32,
        ';', 60,
        '=', 47,
        'R', 58,
        'r', 58,
      );
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(31);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '\\') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(52);
      END_STATE();
    case 4:
      if (lookahead == '0') ADVANCE(50);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 5:
      if (lookahead == '1') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 6:
      if (lookahead == 'C') ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == 'D') ADVANCE(9);
      if (lookahead == 'I') ADVANCE(15);
      END_STATE();
    case 8:
      if (lookahead == 'D') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'E') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'E') ADVANCE(57);
      END_STATE();
    case 11:
      if (lookahead == 'E') ADVANCE(55);
      END_STATE();
    case 12:
      if (lookahead == 'F') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == 'I') ADVANCE(16);
      END_STATE();
    case 14:
      if (lookahead == 'L') ADVANCE(17);
      END_STATE();
    case 15:
      if (lookahead == 'N') ADVANCE(6);
      END_STATE();
    case 16:
      if (lookahead == 'N') ADVANCE(10);
      END_STATE();
    case 17:
      if (lookahead == 'U') ADVANCE(8);
      END_STATE();
    case 18:
      if (lookahead == '\\') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'') ADVANCE(3);
      END_STATE();
    case 19:
      if (lookahead == 'b') ADVANCE(44);
      if (lookahead == 'f') ADVANCE(46);
      if (lookahead == 'l') ADVANCE(33);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 20:
      if (lookahead == 'b') ADVANCE(43);
      if (lookahead == 'f') ADVANCE(45);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(33);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(51);
      END_STATE();
    case 23:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 24:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 25:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 26:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '\n', 31,
        '\r', 1,
        '!', 7,
        '\'', 18,
        '.', 21,
        '0', 50,
        ';', 60,
        '+', 4,
        '-', 4,
      );
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(26);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 27:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '\n', 31,
        '\r', 1,
        '!', 23,
        '"', 2,
        '#', 42,
        '\'', 18,
        '.', 20,
        '0', 50,
        ';', 60,
        '=', 47,
        '+', 4,
        '-', 4,
      );
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(27);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 28:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '\n', 31,
        '\r', 1,
        '!', 23,
        '#', 42,
        '.', 20,
        ':', 32,
        ';', 60,
        '=', 47,
        'R', 5,
        'r', 5,
      );
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(28);
      END_STATE();
    case 29:
      if (eof) ADVANCE(30);
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ';') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(56);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DOTl);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_directive_name);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_register);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_register);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(38);
      if (lookahead == '.' ||
          ('6' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_register);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(41);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_register);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(36);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_register);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(39);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_register);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DOTb);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DOTb);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DOTf);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DOTf);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_number);
      ADVANCE_MAP(
        'B', 51,
        'D', 51,
        'b', 51,
        'd', 51,
        'O', 22,
        'X', 22,
        'o', 22,
        'x', 22,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_alias);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_BANGINCLUDE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_path_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';') ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_BANGDEFINE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '1') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 26},
  [2] = {.lex_state = 26},
  [3] = {.lex_state = 26},
  [4] = {.lex_state = 27},
  [5] = {.lex_state = 28},
  [6] = {.lex_state = 27},
  [7] = {.lex_state = 26},
  [8] = {.lex_state = 28},
  [9] = {.lex_state = 26},
  [10] = {.lex_state = 26},
  [11] = {.lex_state = 26},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 26},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 29},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 29},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 26},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 26},
  [37] = {.lex_state = 26},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 26},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 26},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 26},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 26},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOTl] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_directive_name] = ACTIONS(1),
    [sym_register] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_DOTb] = ACTIONS(1),
    [anon_sym_DOTf] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_char] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_BANGINCLUDE] = ACTIONS(1),
    [anon_sym_BANGDEFINE] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(38),
    [sym__line] = STATE(27),
    [sym_label] = STATE(7),
    [sym_local_label] = STATE(7),
    [sym__statement] = STATE(27),
    [sym_instruction] = STATE(27),
    [sym_directive] = STATE(27),
    [sym_preproc_include] = STATE(27),
    [sym_preproc_define] = STATE(27),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym__line_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym__newline] = ACTIONS(7),
    [anon_sym_DOTl] = ACTIONS(9),
    [sym_directive_name] = ACTIONS(11),
    [anon_sym_BANGINCLUDE] = ACTIONS(13),
    [anon_sym_BANGDEFINE] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_DOTl,
    ACTIONS(11), 1,
      sym_directive_name,
    ACTIONS(13), 1,
      anon_sym_BANGINCLUDE,
    ACTIONS(15), 1,
      anon_sym_BANGDEFINE,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      sym__newline,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(7), 3,
      sym_label,
      sym_local_label,
      aux_sym__line_repeat1,
    STATE(30), 6,
      sym__line,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_preproc_include,
      sym_preproc_define,
  [41] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym__newline,
    ACTIONS(28), 1,
      anon_sym_DOTl,
    ACTIONS(31), 1,
      sym_directive_name,
    ACTIONS(34), 1,
      anon_sym_BANGINCLUDE,
    ACTIONS(37), 1,
      anon_sym_BANGDEFINE,
    ACTIONS(40), 1,
      sym_identifier,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(7), 3,
      sym_label,
      sym_local_label,
      aux_sym__line_repeat1,
    STATE(45), 6,
      sym__line,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_preproc_include,
      sym_preproc_define,
  [82] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_POUND,
    ACTIONS(49), 1,
      anon_sym_EQ,
    ACTIONS(43), 2,
      ts_builtin_sym_end,
      sym__newline,
    ACTIONS(47), 2,
      anon_sym_DOTb,
      anon_sym_DOTf,
    STATE(20), 3,
      sym__argument,
      sym_immediate,
      sym_label_ref,
    ACTIONS(51), 5,
      sym_number,
      sym_char,
      sym_string,
      sym_alias,
      sym_identifier,
  [112] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_POUND,
    ACTIONS(49), 1,
      anon_sym_EQ,
    ACTIONS(55), 1,
      anon_sym_COLON,
    ACTIONS(47), 2,
      anon_sym_DOTb,
      anon_sym_DOTf,
    ACTIONS(53), 2,
      ts_builtin_sym_end,
      sym__newline,
    ACTIONS(57), 2,
      sym_register,
      sym_alias,
    STATE(16), 3,
      sym__operand,
      sym_immediate,
      sym_label_ref,
  [142] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_POUND,
    ACTIONS(49), 1,
      anon_sym_EQ,
    ACTIONS(47), 2,
      anon_sym_DOTb,
      anon_sym_DOTf,
    STATE(24), 3,
      sym__argument,
      sym_immediate,
      sym_label_ref,
    ACTIONS(59), 5,
      sym_number,
      sym_char,
      sym_string,
      sym_alias,
      sym_identifier,
  [168] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_DOTl,
    ACTIONS(11), 1,
      sym_directive_name,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(61), 2,
      ts_builtin_sym_end,
      sym__newline,
    STATE(9), 3,
      sym_label,
      sym_local_label,
      aux_sym__line_repeat1,
    STATE(32), 3,
      sym__statement,
      sym_instruction,
      sym_directive,
  [195] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_POUND,
    ACTIONS(49), 1,
      anon_sym_EQ,
    ACTIONS(47), 2,
      anon_sym_DOTb,
      anon_sym_DOTf,
    ACTIONS(63), 2,
      sym_register,
      sym_alias,
    STATE(23), 3,
      sym__operand,
      sym_immediate,
      sym_label_ref,
  [218] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_DOTl,
    ACTIONS(70), 1,
      sym_directive_name,
    ACTIONS(72), 1,
      sym_identifier,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      sym__newline,
    STATE(9), 3,
      sym_label,
      sym_local_label,
      aux_sym__line_repeat1,
  [240] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 2,
      anon_sym_DOTl,
      sym_directive_name,
    ACTIONS(23), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_BANGINCLUDE,
      anon_sym_BANGDEFINE,
      sym_identifier,
  [255] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 2,
      anon_sym_DOTl,
      sym_directive_name,
    ACTIONS(77), 3,
      ts_builtin_sym_end,
      sym__newline,
      sym_identifier,
  [268] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(81), 3,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COMMA,
  [281] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 2,
      anon_sym_DOTl,
      sym_directive_name,
    ACTIONS(85), 3,
      ts_builtin_sym_end,
      sym__newline,
      sym_identifier,
  [294] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(89), 3,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COMMA,
  [307] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      aux_sym_instruction_repeat1,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      sym__newline,
  [321] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    STATE(15), 1,
      aux_sym_instruction_repeat1,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      sym__newline,
  [335] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      aux_sym_path_token1,
    STATE(34), 1,
      sym_define_value,
    ACTIONS(99), 2,
      ts_builtin_sym_end,
      sym__newline,
  [349] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_COMMA,
    STATE(19), 1,
      aux_sym_directive_repeat1,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      sym__newline,
  [363] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_COMMA,
    STATE(19), 1,
      aux_sym_directive_repeat1,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      sym__newline,
  [377] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_COMMA,
    STATE(18), 1,
      aux_sym_directive_repeat1,
    ACTIONS(112), 2,
      ts_builtin_sym_end,
      sym__newline,
  [391] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      aux_sym_instruction_repeat1,
    ACTIONS(114), 2,
      ts_builtin_sym_end,
      sym__newline,
  [405] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 3,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COMMA,
  [414] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 3,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COMMA,
  [423] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 3,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COMMA,
  [432] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 3,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COMMA,
  [441] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 3,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COMMA,
  [450] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(125), 1,
      sym__newline,
  [460] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 2,
      ts_builtin_sym_end,
      sym__newline,
  [468] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 2,
      ts_builtin_sym_end,
      sym__newline,
  [476] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      sym__newline,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
  [486] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      aux_sym_path_token1,
    STATE(29), 1,
      sym_path,
  [496] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 2,
      ts_builtin_sym_end,
      sym__newline,
  [504] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 2,
      sym_number,
      sym_char,
  [512] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 2,
      ts_builtin_sym_end,
      sym__newline,
  [520] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 2,
      ts_builtin_sym_end,
      sym__newline,
  [528] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_identifier,
  [535] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      sym_identifier,
  [542] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
  [549] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      sym_identifier,
  [556] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_COLON,
  [563] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym_identifier,
  [570] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_EQ,
  [577] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      sym_number,
  [584] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_COLON,
  [591] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      sym__newline,
  [598] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      sym_number,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 112,
  [SMALL_STATE(6)] = 142,
  [SMALL_STATE(7)] = 168,
  [SMALL_STATE(8)] = 195,
  [SMALL_STATE(9)] = 218,
  [SMALL_STATE(10)] = 240,
  [SMALL_STATE(11)] = 255,
  [SMALL_STATE(12)] = 268,
  [SMALL_STATE(13)] = 281,
  [SMALL_STATE(14)] = 294,
  [SMALL_STATE(15)] = 307,
  [SMALL_STATE(16)] = 321,
  [SMALL_STATE(17)] = 335,
  [SMALL_STATE(18)] = 349,
  [SMALL_STATE(19)] = 363,
  [SMALL_STATE(20)] = 377,
  [SMALL_STATE(21)] = 391,
  [SMALL_STATE(22)] = 405,
  [SMALL_STATE(23)] = 414,
  [SMALL_STATE(24)] = 423,
  [SMALL_STATE(25)] = 432,
  [SMALL_STATE(26)] = 441,
  [SMALL_STATE(27)] = 450,
  [SMALL_STATE(28)] = 460,
  [SMALL_STATE(29)] = 468,
  [SMALL_STATE(30)] = 476,
  [SMALL_STATE(31)] = 486,
  [SMALL_STATE(32)] = 496,
  [SMALL_STATE(33)] = 504,
  [SMALL_STATE(34)] = 512,
  [SMALL_STATE(35)] = 520,
  [SMALL_STATE(36)] = 528,
  [SMALL_STATE(37)] = 535,
  [SMALL_STATE(38)] = 542,
  [SMALL_STATE(39)] = 549,
  [SMALL_STATE(40)] = 556,
  [SMALL_STATE(41)] = 563,
  [SMALL_STATE(42)] = 570,
  [SMALL_STATE(43)] = 577,
  [SMALL_STATE(44)] = 584,
  [SMALL_STATE(45)] = 591,
  [SMALL_STATE(46)] = 598,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 1, 0, 2),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__line_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__line_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__line_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_label, 3, 0, 4),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_local_label, 3, 0, 4),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_ref, 2, 0, 4),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2, 0, 1),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label, 2, 0, 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_ref, 3, 0, 6),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 3, 0, 2),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 2, 0, 2),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_define, 2, 0, 4),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_immediate, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_ref, 4, 0, 4),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_ref, 5, 0, 6),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_include, 2, 0, 3),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_define, 3, 0, 5),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_value, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [147] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sra8asm(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
