; generated by ylangc 0.3 (ABI 0.3, docs/ylangc.md)

        .import __stack_top
        .export out
        .export swapper
        .export pswap
        .export sumsq
        .export through
        .export tp
        .export ping
        .export pong
        .export depth
        .export start
        .export start.frame

; start-up code at address 0: set the stack pointer, run the @main function, stop
        .code vector
        .export _start
_start: mova    r14a, =__stack_top     ; SP = the last byte of RAM; the stack grows down
        brl     r12a, =start              ; call start
.l spin:
        br      .b =spin               ; start returned: stop here

        .code

; ------------------------------------------------------------------------------
; swapper: fn(int16, int16, uint8) returns int16 (@recursive: stack frame)
; ------------------------------------------------------------------------------
; stack frame of swapper, 7 bytes, SP + 1 ... SP + 7 after the prologue:
;   SP+1    2   spill slot
;   SP+3    2   spill slot
;   SP+5    1   spill slot
;   SP+6    2   saved return address (r12a)
;   SP+8    2   result (the caller's area)
;   SP+10   2   a (the caller's area)
;   SP+12   2   b (the caller's area)
;   SP+14   1   n (the caller's area)
        .addr   0                      ; header: no static frame (@recursive) ...
        .dword  7                      ; ... and the size of its stack frame
swapper:
        lea     r14a, r14a, #-7        ; SP -= 7: the stack frame
        sto     r12, r14a, #6          ; save the return address
        sto     r13, r14a, #7
; line 11: if (n eq 0) { return a * 10 + b; }
        ldo     r0, r14a, #14          ; r0 = n
        cmp     r0, #0                 ; flags = n - 0
        br.eq   =swapper.2             ; if n eq 0
        br      =swapper.3             ; otherwise
swapper.2:                              ; then: n eq 0
; line 11: if (n eq 0) { return a * 10 + b; }
        ldo     r0, r14a, #10          ; r0 = a (byte 0)
        ldo     r1, r14a, #11          ; r1 = a (byte 1)
        mov     r2, #10                ; r2 = 10 (byte 0)
        mov     r3, #0                 ; r3 = 10 (byte 1)
        sto     r0, r14a, #1           ; spill a (byte 0)
        sto     r1, r14a, #2           ; spill a (byte 1)
        sto     r2, r14a, #3           ; spill 10 (byte 0)
        sto     r3, r14a, #4           ; spill 10 (byte 1)
        ldo     r0, r14a, #1           ; reload a (byte 0)
        ldo     r1, r14a, #2           ; reload a (byte 1)
        str     r0, =__mul16.frame+2   ; argument 1 of __mul16 (byte 0) = r0
        str     r1, =__mul16.frame+3   ; argument 1 of __mul16 (byte 1) = r1
        ldo     r2, r14a, #3           ; reload 10 (byte 0)
        ldo     r3, r14a, #4           ; reload 10 (byte 1)
        str     r2, =__mul16.frame+4   ; argument 2 of __mul16 (byte 0) = r2
        str     r3, =__mul16.frame+5   ; argument 2 of __mul16 (byte 1) = r3
        brl     r12a, =__mul16         ; call a * 10
        ldr     r0, =__mul16.frame     ; r0 = result of __mul16 (byte 0)
        ldr     r1, =__mul16.frame+1   ; r1 = result of __mul16 (byte 1)
        ldo     r2, r14a, #12          ; r2 = b (byte 0)
        ldo     r3, r14a, #13          ; r3 = b (byte 1)
        adds    r0, r0, r2             ; (a * 10) + b, byte 0
        addc    r1, r1, r3             ; ... byte 1 with carry
        sto     r0, r14a, #8           ; result (byte 0) = r0
        sto     r1, r14a, #9           ; result (byte 1) = r1
        br      =swapper.1             ; return
        br      =swapper.4             ; skip the else part
swapper.3:                              ; not: n eq 0
swapper.4:                              ; end of if
; line 12: return swapper(b, a, n - 1);
        ldo     r0, r14a, #12          ; r0 = b (byte 0)
        ldo     r1, r14a, #13          ; r1 = b (byte 1)
        ldo     r2, r14a, #10          ; r2 = a (byte 0)
        ldo     r3, r14a, #11          ; r3 = a (byte 1)
        ldo     r4, r14a, #14          ; r4 = n
        sub     r4, r4, #1             ; n - 1
        sto     r0, r14a, #3           ; spill b (byte 0)
        sto     r1, r14a, #4           ; spill b (byte 1)
        sto     r2, r14a, #1           ; spill a (byte 0)
        sto     r3, r14a, #2           ; spill a (byte 1)
        sto     r4, r14a, #5           ; spill n - 1
        lea     r14a, r14a, #-7        ; SP -= 7: result and arguments of swapper
        ldo     r0, r14a, #10          ; reload b (byte 0)
        ldo     r1, r14a, #11          ; reload b (byte 1)
        sto     r0, r14a, #3           ; argument 1 of swapper (byte 0) = r0
        sto     r1, r14a, #4           ; argument 1 of swapper (byte 1) = r1
        ldo     r2, r14a, #8           ; reload a (byte 0)
        ldo     r3, r14a, #9           ; reload a (byte 1)
        sto     r2, r14a, #5           ; argument 2 of swapper (byte 0) = r2
        sto     r3, r14a, #6           ; argument 2 of swapper (byte 1) = r3
        ldo     r4, r14a, #12          ; reload n - 1
        sto     r4, r14a, #7           ; argument 3 of swapper = r4
        brl     r12a, =swapper         ; call swapper(b, a, n - 1)
        ldo     r0, r14a, #1           ; r0 = result of swapper (byte 0)
        ldo     r1, r14a, #2           ; r1 = result of swapper (byte 1)
        lea     r14a, r14a, #7         ; SP += 7
        sto     r0, r14a, #8           ; result (byte 0) = r0
        sto     r1, r14a, #9           ; result (byte 1) = r1
        br      =swapper.1             ; return
swapper.1:                              ; return
        ldo     r12, r14a, #6          ; reload the return address
        ldo     r13, r14a, #7
        lea     r14a, r14a, #7         ; SP += 7: free the stack frame
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; pswap: fn(point, point, uint8) returns point (@recursive: stack frame)
; ------------------------------------------------------------------------------
; stack frame of pswap, 19 bytes, SP + 1 ... SP + 19 after the prologue:
;   SP+1    2   spill slot
;   SP+3    2   spill slot
;   SP+5    4   scratch: argument q
;   SP+9    4   scratch: argument p
;   SP+13   1   spill slot
;   SP+14   4   scratch: result of pswap(q, p, n - 1)
;   SP+18   2   saved return address (r12a)
;   SP+20   4   result (the caller's area)
;   SP+24   4   p (the caller's area)
;   SP+28   4   q (the caller's area)
;   SP+32   1   n (the caller's area)
        .addr   0                      ; header: no static frame (@recursive) ...
        .dword  19                     ; ... and the size of its stack frame
pswap:
        lea     r14a, r14a, #-19       ; SP -= 19: the stack frame
        sto     r12, r14a, #18         ; save the return address
        sto     r13, r14a, #19
; line 16: if (n eq 0) { return {x = p.x * 10 + q.x, y = p.y * 10 + q.y}; }
        ldo     r0, r14a, #32          ; r0 = n
        cmp     r0, #0                 ; flags = n - 0
        br.eq   =pswap.2               ; if n eq 0
        br      =pswap.3               ; otherwise
pswap.2:                                ; then: n eq 0
; line 16: if (n eq 0) { return {x = p.x * 10 + q.x, y = p.y * 10 + q.y}; }
        ldo     r0, r14a, #24          ; r0 = p.x (byte 0)
        ldo     r1, r14a, #25          ; r1 = p.x (byte 1)
        mov     r2, #10                ; r2 = 10 (byte 0)
        mov     r3, #0                 ; r3 = 10 (byte 1)
        sto     r0, r14a, #1           ; spill p.x (byte 0)
        sto     r1, r14a, #2           ; spill p.x (byte 1)
        sto     r2, r14a, #3           ; spill 10 (byte 0)
        sto     r3, r14a, #4           ; spill 10 (byte 1)
        ldo     r0, r14a, #1           ; reload p.x (byte 0)
        ldo     r1, r14a, #2           ; reload p.x (byte 1)
        str     r0, =__mul16.frame+2   ; argument 1 of __mul16 (byte 0) = r0
        str     r1, =__mul16.frame+3   ; argument 1 of __mul16 (byte 1) = r1
        ldo     r2, r14a, #3           ; reload 10 (byte 0)
        ldo     r3, r14a, #4           ; reload 10 (byte 1)
        str     r2, =__mul16.frame+4   ; argument 2 of __mul16 (byte 0) = r2
        str     r3, =__mul16.frame+5   ; argument 2 of __mul16 (byte 1) = r3
        brl     r12a, =__mul16         ; call p.x * 10
        ldr     r0, =__mul16.frame     ; r0 = result of __mul16 (byte 0)
        ldr     r1, =__mul16.frame+1   ; r1 = result of __mul16 (byte 1)
        ldo     r2, r14a, #28          ; r2 = q.x (byte 0)
        ldo     r3, r14a, #29          ; r3 = q.x (byte 1)
        adds    r0, r0, r2             ; (p.x * 10) + q.x, byte 0
        addc    r1, r1, r3             ; ... byte 1 with carry
        sto     r0, r14a, #20          ; result.x (byte 0) = r0
        sto     r1, r14a, #21          ; result.x (byte 1) = r1
        ldo     r0, r14a, #26          ; r0 = p.y (byte 0)
        ldo     r1, r14a, #27          ; r1 = p.y (byte 1)
        mov     r2, #10                ; r2 = 10 (byte 0)
        mov     r3, #0                 ; r3 = 10 (byte 1)
        sto     r0, r14a, #3           ; spill p.y (byte 0)
        sto     r1, r14a, #4           ; spill p.y (byte 1)
        sto     r2, r14a, #1           ; spill 10 (byte 0)
        sto     r3, r14a, #2           ; spill 10 (byte 1)
        ldo     r0, r14a, #3           ; reload p.y (byte 0)
        ldo     r1, r14a, #4           ; reload p.y (byte 1)
        str     r0, =__mul16.frame+2   ; argument 1 of __mul16 (byte 0) = r0
        str     r1, =__mul16.frame+3   ; argument 1 of __mul16 (byte 1) = r1
        ldo     r2, r14a, #1           ; reload 10 (byte 0)
        ldo     r3, r14a, #2           ; reload 10 (byte 1)
        str     r2, =__mul16.frame+4   ; argument 2 of __mul16 (byte 0) = r2
        str     r3, =__mul16.frame+5   ; argument 2 of __mul16 (byte 1) = r3
        brl     r12a, =__mul16         ; call p.y * 10
        ldr     r0, =__mul16.frame     ; r0 = result of __mul16 (byte 0)
        ldr     r1, =__mul16.frame+1   ; r1 = result of __mul16 (byte 1)
        ldo     r2, r14a, #30          ; r2 = q.y (byte 0)
        ldo     r3, r14a, #31          ; r3 = q.y (byte 1)
        adds    r0, r0, r2             ; (p.y * 10) + q.y, byte 0
        addc    r1, r1, r3             ; ... byte 1 with carry
        sto     r0, r14a, #22          ; result.y (byte 0) = r0
        sto     r1, r14a, #23          ; result.y (byte 1) = r1
        br      =pswap.1               ; return
        br      =pswap.4               ; skip the else part
pswap.3:                                ; not: n eq 0
pswap.4:                                ; end of if
; line 17: return pswap(q, p, n - 1);
        lea     r10a, r14a, #28        ; r10a = @ptr(q)
        mov     r0, r10
        mov     r1, r11
        lea     r10a, r14a, #5         ; r10a = @ptr(scratch: argument q)
        mov     r2, r10
        mov     r3, r11
        sto     r0, r14a, #1           ; spill @ptr(q) (byte 0)
        sto     r1, r14a, #2           ; spill @ptr(q) (byte 1)
        sto     r2, r14a, #3           ; spill @ptr(scratch: argument q) (byte 0)
        sto     r3, r14a, #4           ; spill @ptr(scratch: argument q) (byte 1)
        ldo     r2, r14a, #1           ; r2a = source: q
        ldo     r3, r14a, #2
        ldo     r4, r14a, #3           ; r4a = destination: scratch: argument q
        ldo     r5, r14a, #4
        mov     r6, #4                 ; count = 4 bytes
pswap.5:                                ; copy loop: scratch: argument q = q
        ldi     r0, r2a, #1            ; r0 = byte at source, source + 1
        sti     r0, r4a, #1            ; byte at destination = r0, destination + 1
        subs    r6, r6, #1             ; count - 1
        br.ne   =pswap.5               ; no: next byte
        lea     r10a, r14a, #24        ; r10a = @ptr(p)
        mov     r0, r10
        mov     r1, r11
        lea     r10a, r14a, #9         ; r10a = @ptr(scratch: argument p)
        mov     r2, r10
        mov     r3, r11
        sto     r0, r14a, #3           ; spill @ptr(p) (byte 0)
        sto     r1, r14a, #4           ; spill @ptr(p) (byte 1)
        sto     r2, r14a, #1           ; spill @ptr(scratch: argument p) (byte 0)
        sto     r3, r14a, #2           ; spill @ptr(scratch: argument p) (byte 1)
        ldo     r2, r14a, #3           ; r2a = source: p
        ldo     r3, r14a, #4
        ldo     r4, r14a, #1           ; r4a = destination: scratch: argument p
        ldo     r5, r14a, #2
        mov     r6, #4                 ; count = 4 bytes
pswap.6:                                ; copy loop: scratch: argument p = p
        ldi     r0, r2a, #1            ; r0 = byte at source, source + 1
        sti     r0, r4a, #1            ; byte at destination = r0, destination + 1
        subs    r6, r6, #1             ; count - 1
        br.ne   =pswap.6               ; no: next byte
        ldo     r0, r14a, #32          ; r0 = n
        sub     r0, r0, #1             ; n - 1
        sto     r0, r14a, #13          ; spill n - 1
        lea     r14a, r14a, #-13       ; SP -= 13: result and arguments of pswap
        lea     r10a, r14a, #18        ; r10a = @ptr(scratch: argument q)
        mov     r0, r10
        mov     r1, r11
        lea     r10a, r14a, #5         ; r10a = @ptr(argument 1 of pswap)
        mov     r2, r10
        mov     r3, r11
        sto     r0, r14a, #14          ; spill @ptr(scratch: argument q) (byte 0)
        sto     r1, r14a, #15          ; spill @ptr(scratch: argument q) (byte 1)
        sto     r2, r14a, #16          ; spill @ptr(argument 1 of pswap) (byte 0)
        sto     r3, r14a, #17          ; spill @ptr(argument 1 of pswap) (byte 1)
        ldo     r2, r14a, #14          ; r2a = source: scratch: argument q
        ldo     r3, r14a, #15
        ldo     r4, r14a, #16          ; r4a = destination: argument 1 of pswap
        ldo     r5, r14a, #17
        mov     r6, #4                 ; count = 4 bytes
pswap.7:                                ; copy loop: argument 1 of pswap = scratch: argument q
        ldi     r0, r2a, #1            ; r0 = byte at source, source + 1
        sti     r0, r4a, #1            ; byte at destination = r0, destination + 1
        subs    r6, r6, #1             ; count - 1
        br.ne   =pswap.7               ; no: next byte
        lea     r10a, r14a, #22        ; r10a = @ptr(scratch: argument p)
        mov     r0, r10
        mov     r1, r11
        lea     r10a, r14a, #9         ; r10a = @ptr(argument 2 of pswap)
        mov     r2, r10
        mov     r3, r11
        sto     r0, r14a, #16          ; spill @ptr(scratch: argument p) (byte 0)
        sto     r1, r14a, #17          ; spill @ptr(scratch: argument p) (byte 1)
        sto     r2, r14a, #14          ; spill @ptr(argument 2 of pswap) (byte 0)
        sto     r3, r14a, #15          ; spill @ptr(argument 2 of pswap) (byte 1)
        ldo     r2, r14a, #16          ; r2a = source: scratch: argument p
        ldo     r3, r14a, #17
        ldo     r4, r14a, #14          ; r4a = destination: argument 2 of pswap
        ldo     r5, r14a, #15
        mov     r6, #4                 ; count = 4 bytes
pswap.8:                                ; copy loop: argument 2 of pswap = scratch: argument p
        ldi     r0, r2a, #1            ; r0 = byte at source, source + 1
        sti     r0, r4a, #1            ; byte at destination = r0, destination + 1
        subs    r6, r6, #1             ; count - 1
        br.ne   =pswap.8               ; no: next byte
        ldo     r0, r14a, #26          ; reload n - 1
        sto     r0, r14a, #13          ; argument 3 of pswap = r0
        brl     r12a, =pswap           ; call pswap(q, p, n - 1)
        lea     r10a, r14a, #1         ; r10a = @ptr(result of pswap)
        mov     r0, r10
        mov     r1, r11
        lea     r10a, r14a, #27        ; r10a = @ptr(scratch: result of pswap(q, p, n - 1))
        mov     r2, r10
        mov     r3, r11
        sto     r0, r14a, #14          ; spill @ptr(result of pswap) (byte 0)
        sto     r1, r14a, #15          ; spill @ptr(result of pswap) (byte 1)
        sto     r2, r14a, #16          ; spill @ptr(scratch: result of pswap(q, p, n - 1)) (byte 0)
        sto     r3, r14a, #17          ; spill @ptr(scratch: result of pswap(q, p, n - 1)) (byte 1)
        ldo     r2, r14a, #14          ; r2a = source: result of pswap
        ldo     r3, r14a, #15
        ldo     r4, r14a, #16          ; r4a = destination: scratch: result of pswap(q, p, n - 1)
        ldo     r5, r14a, #17
        mov     r6, #4                 ; count = 4 bytes
pswap.9:                                ; copy loop: scratch: result of pswap(q, p, n - 1) = result of pswap
        ldi     r0, r2a, #1            ; r0 = byte at source, source + 1
        sti     r0, r4a, #1            ; byte at destination = r0, destination + 1
        subs    r6, r6, #1             ; count - 1
        br.ne   =pswap.9               ; no: next byte
        lea     r14a, r14a, #13        ; SP += 13
        lea     r10a, r14a, #14        ; r10a = @ptr(scratch: result of pswap(q, p, n - 1))
        mov     r0, r10
        mov     r1, r11
        lea     r10a, r14a, #20        ; r10a = @ptr(result)
        mov     r2, r10
        mov     r3, r11
        sto     r0, r14a, #3           ; spill @ptr(scratch: result of pswap(q, p, n - 1)) (byte 0)
        sto     r1, r14a, #4           ; spill @ptr(scratch: result of pswap(q, p, n - 1)) (byte 1)
        sto     r2, r14a, #1           ; spill @ptr(result) (byte 0)
        sto     r3, r14a, #2           ; spill @ptr(result) (byte 1)
        ldo     r2, r14a, #3           ; r2a = source: scratch: result of pswap(q, p, n - 1)
        ldo     r3, r14a, #4
        ldo     r4, r14a, #1           ; r4a = destination: result
        ldo     r5, r14a, #2
        mov     r6, #4                 ; count = 4 bytes
pswap.10:                               ; copy loop: result = scratch: result of pswap(q, p, n - 1)
        ldi     r0, r2a, #1            ; r0 = byte at source, source + 1
        sti     r0, r4a, #1            ; byte at destination = r0, destination + 1
        subs    r6, r6, #1             ; count - 1
        br.ne   =pswap.10              ; no: next byte
        br      =pswap.1               ; return
pswap.1:                                ; return
        ldo     r12, r14a, #18         ; reload the return address
        ldo     r13, r14a, #19
        lea     r14a, r14a, #19        ; SP += 19: free the stack frame
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; sumsq: fn(uint16) returns uint32 (@recursive: stack frame)
; ------------------------------------------------------------------------------
; stack frame of sumsq, 20 bytes, SP + 1 ... SP + 20 after the prologue:
;   SP+1    4   mine
;   SP+5    4   spill slot
;   SP+9    4   spill slot
;   SP+13   4   rest
;   SP+17   2   spill slot
;   SP+19   2   saved return address (r12a)
;   SP+21   4   result (the caller's area)
;   SP+25   2   n (the caller's area)
        .addr   0                      ; header: no static frame (@recursive) ...
        .dword  20                     ; ... and the size of its stack frame
sumsq:
        lea     r14a, r14a, #-20       ; SP -= 20: the stack frame
        sto     r12, r14a, #19         ; save the return address
        sto     r13, r14a, #20
; line 22: if (n eq 0) { return 0; }
        ldo     r0, r14a, #25          ; r0 = n (byte 0)
        ldo     r1, r14a, #26          ; r1 = n (byte 1)
        eor     r0, r0, #0             ; byte 0: 0 where n and 0 agree
        eor     r1, r1, #0             ; byte 1: 0 where n and 0 agree
        ord     r0, r1                 ; Z = all bytes equal
        br.eq   =sumsq.2               ; if n eq 0
        br      =sumsq.3               ; otherwise
sumsq.2:                                ; then: n eq 0
; line 22: if (n eq 0) { return 0; }
        mov     r0, #0                 ; r0 = 0 (byte 0)
        mov     r1, #0                 ; r1 = 0 (byte 1)
        mov     r2, #0                 ; r2 = 0 (byte 2)
        mov     r3, #0                 ; r3 = 0 (byte 3)
        sto     r0, r14a, #21          ; result (byte 0) = r0
        sto     r1, r14a, #22          ; result (byte 1) = r1
        sto     r2, r14a, #23          ; result (byte 2) = r2
        sto     r3, r14a, #24          ; result (byte 3) = r3
        br      =sumsq.1               ; return
        br      =sumsq.4               ; skip the else part
sumsq.3:                                ; not: n eq 0
sumsq.4:                                ; end of if
; line 23: var mine: uint32 = @cast(uint32)n * @cast(uint32)n;
        ldo     r0, r14a, #25          ; r0 = n (byte 0)
        ldo     r1, r14a, #26          ; r1 = n (byte 1)
        mov     r2, #0                 ; zero extension of n
        mov     r3, #0                 ; zero extension of n
        ldo     r4, r14a, #25          ; r4 = n (byte 0)
        ldo     r5, r14a, #26          ; r5 = n (byte 1)
        mov     r6, #0                 ; zero extension of n
        mov     r7, #0                 ; zero extension of n
        sto     r0, r14a, #5           ; spill @cast(uint32)n (byte 0)
        sto     r1, r14a, #6           ; spill @cast(uint32)n (byte 1)
        sto     r2, r14a, #7           ; spill @cast(uint32)n (byte 2)
        sto     r3, r14a, #8           ; spill @cast(uint32)n (byte 3)
        sto     r4, r14a, #9           ; spill @cast(uint32)n (byte 0)
        sto     r5, r14a, #10          ; spill @cast(uint32)n (byte 1)
        sto     r6, r14a, #11          ; spill @cast(uint32)n (byte 2)
        sto     r7, r14a, #12          ; spill @cast(uint32)n (byte 3)
        ldo     r0, r14a, #5           ; reload @cast(uint32)n (byte 0)
        ldo     r1, r14a, #6           ; reload @cast(uint32)n (byte 1)
        ldo     r2, r14a, #7           ; reload @cast(uint32)n (byte 2)
        ldo     r3, r14a, #8           ; reload @cast(uint32)n (byte 3)
        str     r0, =__mul32.frame+4   ; argument 1 of __mul32 (byte 0) = r0
        str     r1, =__mul32.frame+5   ; argument 1 of __mul32 (byte 1) = r1
        str     r2, =__mul32.frame+6   ; argument 1 of __mul32 (byte 2) = r2
        str     r3, =__mul32.frame+7   ; argument 1 of __mul32 (byte 3) = r3
        ldo     r4, r14a, #9           ; reload @cast(uint32)n (byte 0)
        ldo     r5, r14a, #10          ; reload @cast(uint32)n (byte 1)
        ldo     r6, r14a, #11          ; reload @cast(uint32)n (byte 2)
        ldo     r7, r14a, #12          ; reload @cast(uint32)n (byte 3)
        str     r4, =__mul32.frame+8   ; argument 2 of __mul32 (byte 0) = r4
        str     r5, =__mul32.frame+9   ; argument 2 of __mul32 (byte 1) = r5
        str     r6, =__mul32.frame+10  ; argument 2 of __mul32 (byte 2) = r6
        str     r7, =__mul32.frame+11  ; argument 2 of __mul32 (byte 3) = r7
        brl     r12a, =__mul32         ; call @cast(uint32)n * @cast(uint32)n
        ldr     r0, =__mul32.frame     ; r0 = result of __mul32 (byte 0)
        ldr     r1, =__mul32.frame+1   ; r1 = result of __mul32 (byte 1)
        ldr     r2, =__mul32.frame+2   ; r2 = result of __mul32 (byte 2)
        ldr     r3, =__mul32.frame+3   ; r3 = result of __mul32 (byte 3)
        sto     r0, r14a, #1           ; mine (byte 0) = r0
        sto     r1, r14a, #2           ; mine (byte 1) = r1
        sto     r2, r14a, #3           ; mine (byte 2) = r2
        sto     r3, r14a, #4           ; mine (byte 3) = r3
; line 24: var rest: uint32 = sumsq(n - 1);
        ldo     r0, r14a, #25          ; r0 = n (byte 0)
        ldo     r1, r14a, #26          ; r1 = n (byte 1)
        subs    r0, r0, #1             ; n - 1, byte 0
        subc    r1, r1, #0             ; ... byte 1 with borrow
        sto     r0, r14a, #17          ; spill n - 1 (byte 0)
        sto     r1, r14a, #18          ; spill n - 1 (byte 1)
        lea     r14a, r14a, #-6        ; SP -= 6: result and arguments of sumsq
        ldo     r0, r14a, #23          ; reload n - 1 (byte 0)
        ldo     r1, r14a, #24          ; reload n - 1 (byte 1)
        sto     r0, r14a, #5           ; argument 1 of sumsq (byte 0) = r0
        sto     r1, r14a, #6           ; argument 1 of sumsq (byte 1) = r1
        brl     r12a, =sumsq           ; call sumsq(n - 1)
        ldo     r0, r14a, #1           ; r0 = result of sumsq (byte 0)
        ldo     r1, r14a, #2           ; r1 = result of sumsq (byte 1)
        ldo     r2, r14a, #3           ; r2 = result of sumsq (byte 2)
        ldo     r3, r14a, #4           ; r3 = result of sumsq (byte 3)
        lea     r14a, r14a, #6         ; SP += 6
        sto     r0, r14a, #13          ; rest (byte 0) = r0
        sto     r1, r14a, #14          ; rest (byte 1) = r1
        sto     r2, r14a, #15          ; rest (byte 2) = r2
        sto     r3, r14a, #16          ; rest (byte 3) = r3
; line 25: return mine + rest;
        ldo     r0, r14a, #1           ; r0 = mine (byte 0)
        ldo     r1, r14a, #2           ; r1 = mine (byte 1)
        ldo     r2, r14a, #3           ; r2 = mine (byte 2)
        ldo     r3, r14a, #4           ; r3 = mine (byte 3)
        ldo     r4, r14a, #13          ; r4 = rest (byte 0)
        ldo     r5, r14a, #14          ; r5 = rest (byte 1)
        ldo     r6, r14a, #15          ; r6 = rest (byte 2)
        ldo     r7, r14a, #16          ; r7 = rest (byte 3)
        adds    r0, r0, r4             ; mine + rest, byte 0
        addcs   r1, r1, r5             ; ... byte 1 with carry
        addcs   r2, r2, r6             ; ... byte 2 with carry
        addc    r3, r3, r7             ; ... byte 3 with carry
        sto     r0, r14a, #21          ; result (byte 0) = r0
        sto     r1, r14a, #22          ; result (byte 1) = r1
        sto     r2, r14a, #23          ; result (byte 2) = r2
        sto     r3, r14a, #24          ; result (byte 3) = r3
        br      =sumsq.1               ; return
sumsq.1:                                ; return
        ldo     r12, r14a, #19         ; reload the return address
        ldo     r13, r14a, #20
        lea     r14a, r14a, #20        ; SP += 20: free the stack frame
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; through: fn(uint8) returns uint16 (@recursive: stack frame)
; ------------------------------------------------------------------------------
; stack frame of through, 13 bytes, SP + 1 ... SP + 13 after the prologue:
;   SP+1    2   mine
;   SP+3    2   spill slot
;   SP+5    2   spill slot
;   SP+7    1   spill slot
;   SP+8    2   spill slot
;   SP+10   2   scratch: result of tp(n - 1)
;   SP+12   2   saved return address (r12a)
;   SP+14   2   result (the caller's area)
;   SP+16   1   n (the caller's area)
        .addr   0                      ; header: no static frame (@recursive) ...
        .dword  13                     ; ... and the size of its stack frame
through:
        lea     r14a, r14a, #-13       ; SP -= 13: the stack frame
        sto     r12, r14a, #12         ; save the return address
        sto     r13, r14a, #13
; line 33: if (n eq 0) { return 1; }
        ldo     r0, r14a, #16          ; r0 = n
        cmp     r0, #0                 ; flags = n - 0
        br.eq   =through.2             ; if n eq 0
        br      =through.3             ; otherwise
through.2:                              ; then: n eq 0
; line 33: if (n eq 0) { return 1; }
        mov     r0, #1                 ; r0 = 1 (byte 0)
        mov     r1, #0                 ; r1 = 1 (byte 1)
        sto     r0, r14a, #14          ; result (byte 0) = r0
        sto     r1, r14a, #15          ; result (byte 1) = r1
        br      =through.1             ; return
        br      =through.4             ; skip the else part
through.3:                              ; not: n eq 0
through.4:                              ; end of if
; line 34: var mine: uint16 = @cast(uint16)n;
        ldo     r0, r14a, #16          ; r0 = n
        mov     r1, #0                 ; zero extension of n
        sto     r0, r14a, #1           ; mine (byte 0) = r0
        sto     r1, r14a, #2           ; mine (byte 1) = r1
; line 35: return mine + tp(n - 1) * 2;
        ldo     r0, r14a, #1           ; r0 = mine (byte 0)
        ldo     r1, r14a, #2           ; r1 = mine (byte 1)
        ldr     r2, =tp                ; r2 = tp (byte 0)
        ldr     r3, =tp+1              ; r3 = tp (byte 1)
        ldo     r4, r14a, #16          ; r4 = n
        sub     r4, r4, #1             ; n - 1
; call through a pointer: the header at the function - 4 holds its static frame, or 0 for a @recursive function
        mov     r10, r2                ; r10a = the function in r3:r2
        mov     r11, r3
        ldo     r5, r10a, #-4          ; its static frame (header), low
        ldo     r6, r10a, #-3          ; ... high
        ord     r5, r6                 ; 0: @recursive, arguments on the stack
        sto     r0, r14a, #3           ; spill mine (byte 0)
        sto     r1, r14a, #4           ; spill mine (byte 1)
        sto     r2, r14a, #5           ; spill tp (byte 0)
        sto     r3, r14a, #6           ; spill tp (byte 1)
        sto     r4, r14a, #7           ; spill n - 1
        sto     r5, r14a, #8           ; spill frame of tp (byte 0)
        sto     r6, r14a, #9           ; spill frame of tp (byte 1)
        br.eq   =through.5
        ldo     r0, r14a, #7           ; reload n - 1
        ldo     r1, r14a, #8           ; reload frame of tp (byte 0)
        ldo     r2, r14a, #9           ; reload frame of tp (byte 1)
        mov     r10, r1                ; r10a = address in r2:r1
        mov     r11, r2
        sto     r0, r10a, #2           ; argument 1 of the call = r0
        ldo     r0, r14a, #5           ; reload tp (byte 0)
        ldo     r1, r14a, #6           ; reload tp (byte 1)
        mov     r10, r0                ; r10a = the function
        mov     r11, r1
        brl     r12a, r10a             ; call tp(n - 1)
        ldo     r0, r14a, #8           ; reload frame of tp (byte 0)
        ldo     r1, r14a, #9           ; reload frame of tp (byte 1)
        mov     r10, r0                ; r10a = address in r1:r0
        mov     r11, r1
        ldo     r2, r10a, #0           ; r2 = result of the call (byte 0)
        ldo     r3, r10a, #1           ; r3 = result of the call (byte 1)
        sto     r2, r14a, #10          ; scratch: result of tp(n - 1) (byte 0) = r2
        sto     r3, r14a, #11          ; scratch: result of tp(n - 1) (byte 1) = r3
        sto     r0, r14a, #8           ; spill frame of tp (byte 0)
        sto     r1, r14a, #9           ; spill frame of tp (byte 1)
        br      =through.6
through.5:                              ; the function is @recursive
        lea     r14a, r14a, #-3        ; SP -= 3: result and arguments of the call
        ldo     r0, r14a, #10          ; reload n - 1
        sto     r0, r14a, #3           ; argument 1 of the call = r0
        ldo     r0, r14a, #8           ; reload tp (byte 0)
        ldo     r1, r14a, #9           ; reload tp (byte 1)
        mov     r10, r0                ; r10a = the function
        mov     r11, r1
        brl     r12a, r10a             ; call tp(n - 1)
        ldo     r0, r14a, #1           ; r0 = result of the call (byte 0)
        ldo     r1, r14a, #2           ; r1 = result of the call (byte 1)
        lea     r14a, r14a, #3         ; SP += 3
        sto     r0, r14a, #10          ; scratch: result of tp(n - 1) (byte 0) = r0
        sto     r1, r14a, #11          ; scratch: result of tp(n - 1) (byte 1) = r1
through.6:
        ldo     r0, r14a, #10          ; reload tp(n - 1) (byte 0)
        ldo     r1, r14a, #11          ; reload tp(n - 1) (byte 1)
        mov     r2, #2                 ; r2 = 2 (byte 0)
        mov     r3, #0                 ; r3 = 2 (byte 1)
        sto     r0, r14a, #10          ; spill tp(n - 1) (byte 0)
        sto     r1, r14a, #11          ; spill tp(n - 1) (byte 1)
        sto     r2, r14a, #5           ; spill 2 (byte 0)
        sto     r3, r14a, #6           ; spill 2 (byte 1)
        ldo     r0, r14a, #10          ; reload tp(n - 1) (byte 0)
        ldo     r1, r14a, #11          ; reload tp(n - 1) (byte 1)
        str     r0, =__mul16.frame+2   ; argument 1 of __mul16 (byte 0) = r0
        str     r1, =__mul16.frame+3   ; argument 1 of __mul16 (byte 1) = r1
        ldo     r2, r14a, #5           ; reload 2 (byte 0)
        ldo     r3, r14a, #6           ; reload 2 (byte 1)
        str     r2, =__mul16.frame+4   ; argument 2 of __mul16 (byte 0) = r2
        str     r3, =__mul16.frame+5   ; argument 2 of __mul16 (byte 1) = r3
        brl     r12a, =__mul16         ; call tp(n - 1) * 2
        ldr     r0, =__mul16.frame     ; r0 = result of __mul16 (byte 0)
        ldr     r1, =__mul16.frame+1   ; r1 = result of __mul16 (byte 1)
        ldo     r2, r14a, #3           ; reload mine (byte 0)
        ldo     r3, r14a, #4           ; reload mine (byte 1)
        adds    r2, r2, r0             ; mine + (tp(n - 1) * 2), byte 0
        addc    r3, r3, r1             ; ... byte 1 with carry
        sto     r2, r14a, #14          ; result (byte 0) = r2
        sto     r3, r14a, #15          ; result (byte 1) = r3
        br      =through.1             ; return
through.1:                              ; return
        ldo     r12, r14a, #12         ; reload the return address
        ldo     r13, r14a, #13
        lea     r14a, r14a, #13        ; SP += 13: free the stack frame
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; pong: fn(uint8, uint16) returns uint16 (@recursive: stack frame)
; ------------------------------------------------------------------------------
; stack frame of pong, 11 bytes, SP + 1 ... SP + 11 after the prologue:
;   SP+1    2   keep
;   SP+3    2   r
;   SP+5    1   spill slot
;   SP+6    2   spill slot
;   SP+8    2   spill slot
;   SP+10   2   saved return address (r12a)
;   SP+12   2   result (the caller's area)
;   SP+14   1   n (the caller's area)
;   SP+15   2   acc (the caller's area)
        .addr   0                      ; header: no static frame (@recursive) ...
        .dword  11                     ; ... and the size of its stack frame
pong:
        lea     r14a, r14a, #-11       ; SP -= 11: the stack frame
        sto     r12, r14a, #10         ; save the return address
        sto     r13, r14a, #11
; line 40: var keep: uint16 = acc + 1;
        ldo     r0, r14a, #15          ; r0 = acc (byte 0)
        ldo     r1, r14a, #16          ; r1 = acc (byte 1)
        adds    r0, r0, #1             ; acc + 1, byte 0
        addc    r1, r1, #0             ; ... byte 1 with carry
        sto     r0, r14a, #1           ; keep (byte 0) = r0
        sto     r1, r14a, #2           ; keep (byte 1) = r1
; line 41: if (n eq 0) { return keep; }
        ldo     r0, r14a, #14          ; r0 = n
        cmp     r0, #0                 ; flags = n - 0
        br.eq   =pong.2                ; if n eq 0
        br      =pong.3                ; otherwise
pong.2:                                 ; then: n eq 0
; line 41: if (n eq 0) { return keep; }
        ldo     r0, r14a, #1           ; r0 = keep (byte 0)
        ldo     r1, r14a, #2           ; r1 = keep (byte 1)
        sto     r0, r14a, #12          ; result (byte 0) = r0
        sto     r1, r14a, #13          ; result (byte 1) = r1
        br      =pong.1                ; return
        br      =pong.4                ; skip the else part
pong.3:                                 ; not: n eq 0
pong.4:                                 ; end of if
; line 42: var r: uint16 = ping(n - 1, keep * 2);
        ldo     r0, r14a, #14          ; r0 = n
        sub     r0, r0, #1             ; n - 1
        ldo     r1, r14a, #1           ; r1 = keep (byte 0)
        ldo     r2, r14a, #2           ; r2 = keep (byte 1)
        mov     r3, #2                 ; r3 = 2 (byte 0)
        mov     r4, #0                 ; r4 = 2 (byte 1)
        sto     r0, r14a, #5           ; spill n - 1
        sto     r1, r14a, #6           ; spill keep (byte 0)
        sto     r2, r14a, #7           ; spill keep (byte 1)
        sto     r3, r14a, #8           ; spill 2 (byte 0)
        sto     r4, r14a, #9           ; spill 2 (byte 1)
        ldo     r0, r14a, #6           ; reload keep (byte 0)
        ldo     r1, r14a, #7           ; reload keep (byte 1)
        str     r0, =__mul16.frame+2   ; argument 1 of __mul16 (byte 0) = r0
        str     r1, =__mul16.frame+3   ; argument 1 of __mul16 (byte 1) = r1
        ldo     r2, r14a, #8           ; reload 2 (byte 0)
        ldo     r3, r14a, #9           ; reload 2 (byte 1)
        str     r2, =__mul16.frame+4   ; argument 2 of __mul16 (byte 0) = r2
        str     r3, =__mul16.frame+5   ; argument 2 of __mul16 (byte 1) = r3
        brl     r12a, =__mul16         ; call keep * 2
        ldr     r0, =__mul16.frame     ; r0 = result of __mul16 (byte 0)
        ldr     r1, =__mul16.frame+1   ; r1 = result of __mul16 (byte 1)
        sto     r0, r14a, #8           ; spill keep * 2 (byte 0)
        sto     r1, r14a, #9           ; spill keep * 2 (byte 1)
        lea     r14a, r14a, #-5        ; SP -= 5: result and arguments of ping
        ldo     r0, r14a, #10          ; reload n - 1
        sto     r0, r14a, #3           ; argument 1 of ping = r0
        ldo     r1, r14a, #13          ; reload keep * 2 (byte 0)
        ldo     r2, r14a, #14          ; reload keep * 2 (byte 1)
        sto     r1, r14a, #4           ; argument 2 of ping (byte 0) = r1
        sto     r2, r14a, #5           ; argument 2 of ping (byte 1) = r2
        brl     r12a, =ping            ; call ping(n - 1, keep * 2)
        ldo     r0, r14a, #1           ; r0 = result of ping (byte 0)
        ldo     r1, r14a, #2           ; r1 = result of ping (byte 1)
        lea     r14a, r14a, #5         ; SP += 5
        sto     r0, r14a, #3           ; r (byte 0) = r0
        sto     r1, r14a, #4           ; r (byte 1) = r1
; line 43: return r + keep;
        ldo     r0, r14a, #3           ; r0 = r (byte 0)
        ldo     r1, r14a, #4           ; r1 = r (byte 1)
        ldo     r2, r14a, #1           ; r2 = keep (byte 0)
        ldo     r3, r14a, #2           ; r3 = keep (byte 1)
        adds    r0, r0, r2             ; r + keep, byte 0
        addc    r1, r1, r3             ; ... byte 1 with carry
        sto     r0, r14a, #12          ; result (byte 0) = r0
        sto     r1, r14a, #13          ; result (byte 1) = r1
        br      =pong.1                ; return
pong.1:                                 ; return
        ldo     r12, r14a, #10         ; reload the return address
        ldo     r13, r14a, #11
        lea     r14a, r14a, #11        ; SP += 11: free the stack frame
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; ping: fn(uint8, uint16) returns uint16 (@recursive: stack frame)
; ------------------------------------------------------------------------------
; stack frame of ping, 9 bytes, SP + 1 ... SP + 9 after the prologue:
;   SP+1    2   keep
;   SP+3    2   r
;   SP+5    1   spill slot
;   SP+6    2   spill slot
;   SP+8    2   saved return address (r12a)
;   SP+10   2   result (the caller's area)
;   SP+12   1   n (the caller's area)
;   SP+13   2   acc (the caller's area)
        .addr   0                      ; header: no static frame (@recursive) ...
        .dword  9                      ; ... and the size of its stack frame
ping:
        lea     r14a, r14a, #-9        ; SP -= 9: the stack frame
        sto     r12, r14a, #8          ; save the return address
        sto     r13, r14a, #9
; line 46: var keep: uint16 = acc + 3;
        ldo     r0, r14a, #13          ; r0 = acc (byte 0)
        ldo     r1, r14a, #14          ; r1 = acc (byte 1)
        adds    r0, r0, #3             ; acc + 3, byte 0
        addc    r1, r1, #0             ; ... byte 1 with carry
        sto     r0, r14a, #1           ; keep (byte 0) = r0
        sto     r1, r14a, #2           ; keep (byte 1) = r1
; line 47: if (n eq 0) { return keep; }
        ldo     r0, r14a, #12          ; r0 = n
        cmp     r0, #0                 ; flags = n - 0
        br.eq   =ping.2                ; if n eq 0
        br      =ping.3                ; otherwise
ping.2:                                 ; then: n eq 0
; line 47: if (n eq 0) { return keep; }
        ldo     r0, r14a, #1           ; r0 = keep (byte 0)
        ldo     r1, r14a, #2           ; r1 = keep (byte 1)
        sto     r0, r14a, #10          ; result (byte 0) = r0
        sto     r1, r14a, #11          ; result (byte 1) = r1
        br      =ping.1                ; return
        br      =ping.4                ; skip the else part
ping.3:                                 ; not: n eq 0
ping.4:                                 ; end of if
; line 48: var r: uint16 = pong(n - 1, keep);
        ldo     r0, r14a, #12          ; r0 = n
        sub     r0, r0, #1             ; n - 1
        ldo     r1, r14a, #1           ; r1 = keep (byte 0)
        ldo     r2, r14a, #2           ; r2 = keep (byte 1)
        sto     r0, r14a, #5           ; spill n - 1
        sto     r1, r14a, #6           ; spill keep (byte 0)
        sto     r2, r14a, #7           ; spill keep (byte 1)
        lea     r14a, r14a, #-5        ; SP -= 5: result and arguments of pong
        ldo     r0, r14a, #10          ; reload n - 1
        sto     r0, r14a, #3           ; argument 1 of pong = r0
        ldo     r1, r14a, #11          ; reload keep (byte 0)
        ldo     r2, r14a, #12          ; reload keep (byte 1)
        sto     r1, r14a, #4           ; argument 2 of pong (byte 0) = r1
        sto     r2, r14a, #5           ; argument 2 of pong (byte 1) = r2
        brl     r12a, =pong            ; call pong(n - 1, keep)
        ldo     r0, r14a, #1           ; r0 = result of pong (byte 0)
        ldo     r1, r14a, #2           ; r1 = result of pong (byte 1)
        lea     r14a, r14a, #5         ; SP += 5
        sto     r0, r14a, #3           ; r (byte 0) = r0
        sto     r1, r14a, #4           ; r (byte 1) = r1
; line 49: return r - keep;
        ldo     r0, r14a, #3           ; r0 = r (byte 0)
        ldo     r1, r14a, #4           ; r1 = r (byte 1)
        ldo     r2, r14a, #1           ; r2 = keep (byte 0)
        ldo     r3, r14a, #2           ; r3 = keep (byte 1)
        subs    r0, r0, r2             ; r - keep, byte 0
        subc    r1, r1, r3             ; ... byte 1 with borrow
        sto     r0, r14a, #10          ; result (byte 0) = r0
        sto     r1, r14a, #11          ; result (byte 1) = r1
        br      =ping.1                ; return
ping.1:                                 ; return
        ldo     r12, r14a, #8          ; reload the return address
        ldo     r13, r14a, #9
        lea     r14a, r14a, #9         ; SP += 9: free the stack frame
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; depth: fn(uint8, *uint8) (@recursive: stack frame)
; ------------------------------------------------------------------------------
; stack frame of depth, 5 bytes, SP + 1 ... SP + 5 after the prologue:
;   SP+1    1   spill slot
;   SP+2    2   spill slot
;   SP+4    2   saved return address (r12a)
;   SP+6    1   n (the caller's area)
;   SP+7    2   p (the caller's area)
        .addr   0                      ; header: no static frame (@recursive) ...
        .dword  5                      ; ... and the size of its stack frame
depth:
        lea     r14a, r14a, #-5        ; SP -= 5: the stack frame
        sto     r12, r14a, #4          ; save the return address
        sto     r13, r14a, #5
; line 53: if (n eq 0) { return; }
        ldo     r0, r14a, #6           ; r0 = n
        cmp     r0, #0                 ; flags = n - 0
        br.eq   =depth.2               ; if n eq 0
        br      =depth.3               ; otherwise
depth.2:                                ; then: n eq 0
; line 53: if (n eq 0) { return; }
        br      =depth.1               ; return
        br      =depth.4               ; skip the else part
depth.3:                                ; not: n eq 0
depth.4:                                ; end of if
; line 54: [p] += 1;
        ldo     r0, r14a, #7           ; r0 = p (byte 0)
        ldo     r1, r14a, #8           ; r1 = p (byte 1)
        mov     r10, r0                ; r10a = address in r1:r0
        mov     r11, r1
        ldo     r2, r10a, #0           ; r2 = [p]
        add     r2, r2, #1             ; [p] + 1
        mov     r10, r0                ; r10a = address in r1:r0
        mov     r11, r1
        sto     r2, r10a, #0           ; [p] = r2
; line 55: depth(n - 1, p);
        ldo     r0, r14a, #6           ; r0 = n
        sub     r0, r0, #1             ; n - 1
        ldo     r1, r14a, #7           ; r1 = p (byte 0)
        ldo     r2, r14a, #8           ; r2 = p (byte 1)
        sto     r0, r14a, #1           ; spill n - 1
        sto     r1, r14a, #2           ; spill p (byte 0)
        sto     r2, r14a, #3           ; spill p (byte 1)
        lea     r14a, r14a, #-3        ; SP -= 3: result and arguments of depth
        ldo     r0, r14a, #4           ; reload n - 1
        sto     r0, r14a, #1           ; argument 1 of depth = r0
        ldo     r1, r14a, #5           ; reload p (byte 0)
        ldo     r2, r14a, #6           ; reload p (byte 1)
        sto     r1, r14a, #2           ; argument 2 of depth (byte 0) = r1
        sto     r2, r14a, #3           ; argument 2 of depth (byte 1) = r2
        brl     r12a, =depth           ; call depth(n - 1, p)
        lea     r14a, r14a, #3         ; SP += 3
depth.1:                                ; return
        ldo     r12, r14a, #4          ; reload the return address
        ldo     r13, r14a, #5
        lea     r14a, r14a, #5         ; SP += 5: free the stack frame
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; start: fn()
; ------------------------------------------------------------------------------
        .addr   =start.frame           ; header: the frame of start ...
        .dword  24                     ; ... and its size
start:
        str     r12, =start.frame      ; save the return address
        str     r13, =start.frame+1
; line 60: out[0] = @cast(int32)swapper(1, 2, 3);
        mov     r0, #1                 ; r0 = 1 (byte 0)
        mov     r1, #0                 ; r1 = 1 (byte 1)
        mov     r2, #2                 ; r2 = 2 (byte 0)
        mov     r3, #0                 ; r3 = 2 (byte 1)
        mov     r4, #3                 ; r4 = 3
        str     r0, =start.frame+2     ; spill 1 (byte 0)
        str     r1, =start.frame+3     ; spill 1 (byte 1)
        str     r2, =start.frame+4     ; spill 2 (byte 0)
        str     r3, =start.frame+5     ; spill 2 (byte 1)
        str     r4, =start.frame+6     ; spill 3
        lea     r14a, r14a, #-7        ; SP -= 7: result and arguments of swapper
        ldr     r0, =start.frame+2     ; reload 1 (byte 0)
        ldr     r1, =start.frame+3     ; reload 1 (byte 1)
        sto     r0, r14a, #3           ; argument 1 of swapper (byte 0) = r0
        sto     r1, r14a, #4           ; argument 1 of swapper (byte 1) = r1
        ldr     r2, =start.frame+4     ; reload 2 (byte 0)
        ldr     r3, =start.frame+5     ; reload 2 (byte 1)
        sto     r2, r14a, #5           ; argument 2 of swapper (byte 0) = r2
        sto     r3, r14a, #6           ; argument 2 of swapper (byte 1) = r3
        ldr     r4, =start.frame+6     ; reload 3
        sto     r4, r14a, #7           ; argument 3 of swapper = r4
        brl     r12a, =swapper         ; call swapper(1, 2, 3)
        ldo     r0, r14a, #1           ; r0 = result of swapper (byte 0)
        ldo     r1, r14a, #2           ; r1 = result of swapper (byte 1)
        lea     r14a, r14a, #7         ; SP += 7
        mov     r2, #0                 ; sign extension of swapper(1, 2, 3): 0 ...
        andd    r1, #128               ; ... is the sign bit set?
        mov.ne  r2, #255               ; ... then 0xFF
        mov     r3, r2                 ; sign extension, next byte
        str     r0, =out               ; out[0] (byte 0) = r0
        str     r1, =out+1             ; out[0] (byte 1) = r1
        str     r2, =out+2             ; out[0] (byte 2) = r2
        str     r3, =out+3             ; out[0] (byte 3) = r3
; line 61: out[1] = @cast(int32)swapper(1, 2, 4);
        mov     r0, #1                 ; r0 = 1 (byte 0)
        mov     r1, #0                 ; r1 = 1 (byte 1)
        mov     r2, #2                 ; r2 = 2 (byte 0)
        mov     r3, #0                 ; r3 = 2 (byte 1)
        mov     r4, #4                 ; r4 = 4
        str     r0, =start.frame+4     ; spill 1 (byte 0)
        str     r1, =start.frame+5     ; spill 1 (byte 1)
        str     r2, =start.frame+2     ; spill 2 (byte 0)
        str     r3, =start.frame+3     ; spill 2 (byte 1)
        str     r4, =start.frame+6     ; spill 4
        lea     r14a, r14a, #-7        ; SP -= 7: result and arguments of swapper
        ldr     r0, =start.frame+4     ; reload 1 (byte 0)
        ldr     r1, =start.frame+5     ; reload 1 (byte 1)
        sto     r0, r14a, #3           ; argument 1 of swapper (byte 0) = r0
        sto     r1, r14a, #4           ; argument 1 of swapper (byte 1) = r1
        ldr     r2, =start.frame+2     ; reload 2 (byte 0)
        ldr     r3, =start.frame+3     ; reload 2 (byte 1)
        sto     r2, r14a, #5           ; argument 2 of swapper (byte 0) = r2
        sto     r3, r14a, #6           ; argument 2 of swapper (byte 1) = r3
        ldr     r4, =start.frame+6     ; reload 4
        sto     r4, r14a, #7           ; argument 3 of swapper = r4
        brl     r12a, =swapper         ; call swapper(1, 2, 4)
        ldo     r0, r14a, #1           ; r0 = result of swapper (byte 0)
        ldo     r1, r14a, #2           ; r1 = result of swapper (byte 1)
        lea     r14a, r14a, #7         ; SP += 7
        mov     r2, #0                 ; sign extension of swapper(1, 2, 4): 0 ...
        andd    r1, #128               ; ... is the sign bit set?
        mov.ne  r2, #255               ; ... then 0xFF
        mov     r3, r2                 ; sign extension, next byte
        str     r0, =out+4             ; out[1] (byte 0) = r0
        str     r1, =out+5             ; out[1] (byte 1) = r1
        str     r2, =out+6             ; out[1] (byte 2) = r2
        str     r3, =out+7             ; out[1] (byte 3) = r3
; line 62: var r: point = pswap({x = 1, y = 3}, {x = 2, y = 4}, 5);
        mov     r0, #1                 ; r0 = 1 (byte 0)
        mov     r1, #0                 ; r1 = 1 (byte 1)
        str     r0, =start.frame+11    ; scratch: argument {...}.x (byte 0) = r0
        str     r1, =start.frame+12    ; scratch: argument {...}.x (byte 1) = r1
        mov     r0, #3                 ; r0 = 3 (byte 0)
        mov     r1, #0                 ; r1 = 3 (byte 1)
        str     r0, =start.frame+13    ; scratch: argument {...}.y (byte 0) = r0
        str     r1, =start.frame+14    ; scratch: argument {...}.y (byte 1) = r1
        mov     r0, #2                 ; r0 = 2 (byte 0)
        mov     r1, #0                 ; r1 = 2 (byte 1)
        str     r0, =start.frame+15    ; scratch: argument {...}.x (byte 0) = r0
        str     r1, =start.frame+16    ; scratch: argument {...}.x (byte 1) = r1
        mov     r0, #4                 ; r0 = 4 (byte 0)
        mov     r1, #0                 ; r1 = 4 (byte 1)
        str     r0, =start.frame+17    ; scratch: argument {...}.y (byte 0) = r0
        str     r1, =start.frame+18    ; scratch: argument {...}.y (byte 1) = r1
        mov     r0, #5                 ; r0 = 5
        str     r0, =start.frame+6     ; spill 5
        lea     r14a, r14a, #-13       ; SP -= 13: result and arguments of pswap
        mova    r10a, =start.frame+11  ; r10a = @ptr(scratch: argument {...})
        mov     r0, r10
        mov     r1, r11
        lea     r10a, r14a, #5         ; r10a = @ptr(argument 1 of pswap)
        mov     r2, r10
        mov     r3, r11
        str     r0, =start.frame+2     ; spill @ptr(scratch: argument {...}) (byte 0)
        str     r1, =start.frame+3     ; spill @ptr(scratch: argument {...}) (byte 1)
        str     r2, =start.frame+4     ; spill @ptr(argument 1 of pswap) (byte 0)
        str     r3, =start.frame+5     ; spill @ptr(argument 1 of pswap) (byte 1)
        ldr     r2, =start.frame+2     ; r2a = source: scratch: argument {...}
        ldr     r3, =start.frame+3
        ldr     r4, =start.frame+4     ; r4a = destination: argument 1 of pswap
        ldr     r5, =start.frame+5
        mov     r6, #4                 ; count = 4 bytes
start.2:                                ; copy loop: argument 1 of pswap = scratch: argument {...}
        ldi     r0, r2a, #1            ; r0 = byte at source, source + 1
        sti     r0, r4a, #1            ; byte at destination = r0, destination + 1
        subs    r6, r6, #1             ; count - 1
        br.ne   =start.2               ; no: next byte
        mova    r10a, =start.frame+15  ; r10a = @ptr(scratch: argument {...})
        mov     r0, r10
        mov     r1, r11
        lea     r10a, r14a, #9         ; r10a = @ptr(argument 2 of pswap)
        mov     r2, r10
        mov     r3, r11
        str     r0, =start.frame+4     ; spill @ptr(scratch: argument {...}) (byte 0)
        str     r1, =start.frame+5     ; spill @ptr(scratch: argument {...}) (byte 1)
        str     r2, =start.frame+2     ; spill @ptr(argument 2 of pswap) (byte 0)
        str     r3, =start.frame+3     ; spill @ptr(argument 2 of pswap) (byte 1)
        ldr     r2, =start.frame+4     ; r2a = source: scratch: argument {...}
        ldr     r3, =start.frame+5
        ldr     r4, =start.frame+2     ; r4a = destination: argument 2 of pswap
        ldr     r5, =start.frame+3
        mov     r6, #4                 ; count = 4 bytes
start.3:                                ; copy loop: argument 2 of pswap = scratch: argument {...}
        ldi     r0, r2a, #1            ; r0 = byte at source, source + 1
        sti     r0, r4a, #1            ; byte at destination = r0, destination + 1
        subs    r6, r6, #1             ; count - 1
        br.ne   =start.3               ; no: next byte
        ldr     r0, =start.frame+6     ; reload 5
        sto     r0, r14a, #13          ; argument 3 of pswap = r0
        brl     r12a, =pswap           ; call pswap({...}, {...}, 5)
        lea     r10a, r14a, #1         ; r10a = @ptr(result of pswap)
        mov     r0, r10
        mov     r1, r11
        mova    r10a, =start.frame+19  ; r10a = @ptr(scratch: result of pswap({...}, {...}, 5))
        mov     r2, r10
        mov     r3, r11
        str     r0, =start.frame+2     ; spill @ptr(result of pswap) (byte 0)
        str     r1, =start.frame+3     ; spill @ptr(result of pswap) (byte 1)
        str     r2, =start.frame+4     ; spill @ptr(scratch: result of pswap({...}, {...}, 5)) (byte 0)
        str     r3, =start.frame+5     ; spill @ptr(scratch: result of pswap({...}, {...}, 5)) (byte 1)
        ldr     r2, =start.frame+2     ; r2a = source: result of pswap
        ldr     r3, =start.frame+3
        ldr     r4, =start.frame+4     ; r4a = destination: scratch: result of pswap({...}, {...}, 5)
        ldr     r5, =start.frame+5
        mov     r6, #4                 ; count = 4 bytes
start.4:                                ; copy loop: scratch: result of pswap({...}, {...}, 5) = result of pswap
        ldi     r0, r2a, #1            ; r0 = byte at source, source + 1
        sti     r0, r4a, #1            ; byte at destination = r0, destination + 1
        subs    r6, r6, #1             ; count - 1
        br.ne   =start.4               ; no: next byte
        lea     r14a, r14a, #13        ; SP += 13
        mova    r10a, =start.frame+19  ; r10a = @ptr(scratch: result of pswap({...}, {...}, 5))
        mov     r0, r10
        mov     r1, r11
        mova    r10a, =start.frame+7   ; r10a = @ptr(r)
        mov     r2, r10
        mov     r3, r11
        str     r0, =start.frame+4     ; spill @ptr(scratch: result of pswap({...}, {...}, 5)) (byte 0)
        str     r1, =start.frame+5     ; spill @ptr(scratch: result of pswap({...}, {...}, 5)) (byte 1)
        str     r2, =start.frame+2     ; spill @ptr(r) (byte 0)
        str     r3, =start.frame+3     ; spill @ptr(r) (byte 1)
        ldr     r2, =start.frame+4     ; r2a = source: scratch: result of pswap({...}, {...}, 5)
        ldr     r3, =start.frame+5
        ldr     r4, =start.frame+2     ; r4a = destination: r
        ldr     r5, =start.frame+3
        mov     r6, #4                 ; count = 4 bytes
start.5:                                ; copy loop: r = scratch: result of pswap({...}, {...}, 5)
        ldi     r0, r2a, #1            ; r0 = byte at source, source + 1
        sti     r0, r4a, #1            ; byte at destination = r0, destination + 1
        subs    r6, r6, #1             ; count - 1
        br.ne   =start.5               ; no: next byte
; line 63: out[2] = @cast(int32)r.x;
        ldr     r0, =start.frame+7     ; r0 = r.x (byte 0)
        ldr     r1, =start.frame+8     ; r1 = r.x (byte 1)
        mov     r2, #0                 ; sign extension of r.x: 0 ...
        andd    r1, #128               ; ... is the sign bit set?
        mov.ne  r2, #255               ; ... then 0xFF
        mov     r3, r2                 ; sign extension, next byte
        str     r0, =out+8             ; out[2] (byte 0) = r0
        str     r1, =out+9             ; out[2] (byte 1) = r1
        str     r2, =out+10            ; out[2] (byte 2) = r2
        str     r3, =out+11            ; out[2] (byte 3) = r3
; line 64: out[3] = @cast(int32)r.y;
        ldr     r0, =start.frame+9     ; r0 = r.y (byte 0)
        ldr     r1, =start.frame+10    ; r1 = r.y (byte 1)
        mov     r2, #0                 ; sign extension of r.y: 0 ...
        andd    r1, #128               ; ... is the sign bit set?
        mov.ne  r2, #255               ; ... then 0xFF
        mov     r3, r2                 ; sign extension, next byte
        str     r0, =out+12            ; out[3] (byte 0) = r0
        str     r1, =out+13            ; out[3] (byte 1) = r1
        str     r2, =out+14            ; out[3] (byte 2) = r2
        str     r3, =out+15            ; out[3] (byte 3) = r3
; line 65: out[4] = @as(int32)sumsq(20);
        mov     r0, #20                ; r0 = 20 (byte 0)
        mov     r1, #0                 ; r1 = 20 (byte 1)
        str     r0, =start.frame+2     ; spill 20 (byte 0)
        str     r1, =start.frame+3     ; spill 20 (byte 1)
        lea     r14a, r14a, #-6        ; SP -= 6: result and arguments of sumsq
        ldr     r0, =start.frame+2     ; reload 20 (byte 0)
        ldr     r1, =start.frame+3     ; reload 20 (byte 1)
        sto     r0, r14a, #5           ; argument 1 of sumsq (byte 0) = r0
        sto     r1, r14a, #6           ; argument 1 of sumsq (byte 1) = r1
        brl     r12a, =sumsq           ; call sumsq(20)
        ldo     r0, r14a, #1           ; r0 = result of sumsq (byte 0)
        ldo     r1, r14a, #2           ; r1 = result of sumsq (byte 1)
        ldo     r2, r14a, #3           ; r2 = result of sumsq (byte 2)
        ldo     r3, r14a, #4           ; r3 = result of sumsq (byte 3)
        lea     r14a, r14a, #6         ; SP += 6
        str     r0, =out+16            ; out[4] (byte 0) = r0
        str     r1, =out+17            ; out[4] (byte 1) = r1
        str     r2, =out+18            ; out[4] (byte 2) = r2
        str     r3, =out+19            ; out[4] (byte 3) = r3
; line 66: out[5] = @cast(int32)through(5);
        mov     r0, #5                 ; r0 = 5
        str     r0, =start.frame+6     ; spill 5
        lea     r14a, r14a, #-3        ; SP -= 3: result and arguments of through
        ldr     r0, =start.frame+6     ; reload 5
        sto     r0, r14a, #3           ; argument 1 of through = r0
        brl     r12a, =through         ; call through(5)
        ldo     r0, r14a, #1           ; r0 = result of through (byte 0)
        ldo     r1, r14a, #2           ; r1 = result of through (byte 1)
        lea     r14a, r14a, #3         ; SP += 3
        mov     r2, #0                 ; zero extension of through(5)
        mov     r3, #0                 ; zero extension of through(5)
        str     r0, =out+20            ; out[5] (byte 0) = r0
        str     r1, =out+21            ; out[5] (byte 1) = r1
        str     r2, =out+22            ; out[5] (byte 2) = r2
        str     r3, =out+23            ; out[5] (byte 3) = r3
; line 67: out[6] = @cast(int32)ping(7, 1);
        mov     r0, #7                 ; r0 = 7
        mov     r1, #1                 ; r1 = 1 (byte 0)
        mov     r2, #0                 ; r2 = 1 (byte 1)
        str     r0, =start.frame+6     ; spill 7
        str     r1, =start.frame+2     ; spill 1 (byte 0)
        str     r2, =start.frame+3     ; spill 1 (byte 1)
        lea     r14a, r14a, #-5        ; SP -= 5: result and arguments of ping
        ldr     r0, =start.frame+6     ; reload 7
        sto     r0, r14a, #3           ; argument 1 of ping = r0
        ldr     r1, =start.frame+2     ; reload 1 (byte 0)
        ldr     r2, =start.frame+3     ; reload 1 (byte 1)
        sto     r1, r14a, #4           ; argument 2 of ping (byte 0) = r1
        sto     r2, r14a, #5           ; argument 2 of ping (byte 1) = r2
        brl     r12a, =ping            ; call ping(7, 1)
        ldo     r0, r14a, #1           ; r0 = result of ping (byte 0)
        ldo     r1, r14a, #2           ; r1 = result of ping (byte 1)
        lea     r14a, r14a, #5         ; SP += 5
        mov     r2, #0                 ; zero extension of ping(7, 1)
        mov     r3, #0                 ; zero extension of ping(7, 1)
        str     r0, =out+24            ; out[6] (byte 0) = r0
        str     r1, =out+25            ; out[6] (byte 1) = r1
        str     r2, =out+26            ; out[6] (byte 2) = r2
        str     r3, =out+27            ; out[6] (byte 3) = r3
; line 68: var cnt: uint8 = 0;
        mov     r0, #0                 ; r0 = 0
        str     r0, =start.frame+23    ; cnt = r0
; line 69: depth(200, @ptr(cnt));
        mov     r0, #200               ; r0 = 200
        mova    r10a, =start.frame+23  ; r10a = @ptr(cnt)
        mov     r1, r10
        mov     r2, r11
        str     r0, =start.frame+6     ; spill 200
        str     r1, =start.frame+2     ; spill @ptr(cnt) (byte 0)
        str     r2, =start.frame+3     ; spill @ptr(cnt) (byte 1)
        lea     r14a, r14a, #-3        ; SP -= 3: result and arguments of depth
        ldr     r0, =start.frame+6     ; reload 200
        sto     r0, r14a, #1           ; argument 1 of depth = r0
        ldr     r1, =start.frame+2     ; reload @ptr(cnt) (byte 0)
        ldr     r2, =start.frame+3     ; reload @ptr(cnt) (byte 1)
        sto     r1, r14a, #2           ; argument 2 of depth (byte 0) = r1
        sto     r2, r14a, #3           ; argument 2 of depth (byte 1) = r2
        brl     r12a, =depth           ; call depth(200, @ptr(cnt))
        lea     r14a, r14a, #3         ; SP += 3
; line 70: out[7] = @cast(int32)cnt;
        ldr     r0, =start.frame+23    ; r0 = cnt
        mov     r1, #0                 ; zero extension of cnt
        mov     r2, #0                 ; zero extension of cnt
        mov     r3, #0                 ; zero extension of cnt
        str     r0, =out+28            ; out[7] (byte 0) = r0
        str     r1, =out+29            ; out[7] (byte 1) = r1
        str     r2, =out+30            ; out[7] (byte 2) = r2
        str     r3, =out+31            ; out[7] (byte 3) = r3
start.1:                                ; return
        ldr     r12, =start.frame      ; reload the return address
        ldr     r13, =start.frame+1
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; __mul16: fn(uint16, uint16) returns uint16
; ------------------------------------------------------------------------------
        .addr   =__mul16.frame         ; header: the frame of __mul16 ...
        .dword  10                     ; ... and its size
__mul16:
        str     r12, =__mul16.frame+6  ; save the return address
        str     r13, =__mul16.frame+7
        mov     r0, #0                 ; r0 = 0 (byte 0)
        mov     r1, #0                 ; r1 = 0 (byte 1)
        str     r0, =__mul16.frame+8   ; r (byte 0) = r0
        str     r1, =__mul16.frame+9   ; r (byte 1) = r1
__mul16.2:                              ; loop
        ldr     r0, =__mul16.frame+4   ; r0 = b (byte 0)
        ldr     r1, =__mul16.frame+5   ; r1 = b (byte 1)
        eor     r0, r0, #0             ; byte 0: 0 where b and 0 agree
        eor     r1, r1, #0             ; byte 1: 0 where b and 0 agree
        ord     r0, r1                 ; Z = all bytes equal
        br.eq   =__mul16.4             ; if b eq 0
        br      =__mul16.5             ; otherwise
__mul16.4:                              ; then: b eq 0
        br      =__mul16.3             ; break
        br      =__mul16.6             ; skip the else part
__mul16.5:                              ; not: b eq 0
__mul16.6:                              ; end of if
        ldr     r0, =__mul16.frame+4   ; r0 = b (byte 0)
        ldr     r1, =__mul16.frame+5   ; r1 = b (byte 1)
        and     r0, r0, #1             ; b & 1 (byte 0)
        and     r1, r1, #0             ; b & 1 (byte 1)
        eor     r0, r0, #0             ; byte 0: 0 where b & 1 and 0 agree
        eor     r1, r1, #0             ; byte 1: 0 where b & 1 and 0 agree
        ord     r0, r1                 ; Z = all bytes equal
        br.ne   =__mul16.7             ; if (b & 1) ne 0
        br      =__mul16.8             ; otherwise
__mul16.7:                              ; then: (b & 1) ne 0
        ldr     r0, =__mul16.frame+8   ; r0 = r (byte 0)
        ldr     r1, =__mul16.frame+9   ; r1 = r (byte 1)
        ldr     r2, =__mul16.frame+2   ; r2 = a (byte 0)
        ldr     r3, =__mul16.frame+3   ; r3 = a (byte 1)
        adds    r0, r0, r2             ; r + a, byte 0
        addc    r1, r1, r3             ; ... byte 1 with carry
        str     r0, =__mul16.frame+8   ; r (byte 0) = r0
        str     r1, =__mul16.frame+9   ; r (byte 1) = r1
        br      =__mul16.9             ; skip the else part
__mul16.8:                              ; not: (b & 1) ne 0
__mul16.9:                              ; end of if
        ldr     r0, =__mul16.frame+2   ; r0 = a (byte 0)
        ldr     r1, =__mul16.frame+3   ; r1 = a (byte 1)
        lsls    r0, r0                 ; a shl 1: step 1 of 1
        csl     r1, r1                 ; ... carry into byte 1
        str     r0, =__mul16.frame+2   ; a (byte 0) = r0
        str     r1, =__mul16.frame+3   ; a (byte 1) = r1
        ldr     r0, =__mul16.frame+4   ; r0 = b (byte 0)
        ldr     r1, =__mul16.frame+5   ; r1 = b (byte 1)
        lsrs    r1, r1                 ; b shr 1: step 1 of 1
        csr     r0, r0                 ; ... carry into byte 0
        str     r0, =__mul16.frame+4   ; b (byte 0) = r0
        str     r1, =__mul16.frame+5   ; b (byte 1) = r1
        br      =__mul16.2             ; again
__mul16.3:                              ; end of loop
        ldr     r0, =__mul16.frame+8   ; r0 = r (byte 0)
        ldr     r1, =__mul16.frame+9   ; r1 = r (byte 1)
        str     r0, =__mul16.frame     ; result (byte 0) = r0
        str     r1, =__mul16.frame+1   ; result (byte 1) = r1
        br      =__mul16.1             ; return
__mul16.1:                              ; return
        ldr     r12, =__mul16.frame+6  ; reload the return address
        ldr     r13, =__mul16.frame+7
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; __mul32: fn(uint32, uint32) returns uint32
; ------------------------------------------------------------------------------
        .addr   =__mul32.frame         ; header: the frame of __mul32 ...
        .dword  18                     ; ... and its size
__mul32:
        str     r12, =__mul32.frame+12 ; save the return address
        str     r13, =__mul32.frame+13
        mov     r0, #0                 ; r0 = 0 (byte 0)
        mov     r1, #0                 ; r1 = 0 (byte 1)
        mov     r2, #0                 ; r2 = 0 (byte 2)
        mov     r3, #0                 ; r3 = 0 (byte 3)
        str     r0, =__mul32.frame+14  ; r (byte 0) = r0
        str     r1, =__mul32.frame+15  ; r (byte 1) = r1
        str     r2, =__mul32.frame+16  ; r (byte 2) = r2
        str     r3, =__mul32.frame+17  ; r (byte 3) = r3
__mul32.2:                              ; loop
        ldr     r0, =__mul32.frame+8   ; r0 = b (byte 0)
        ldr     r1, =__mul32.frame+9   ; r1 = b (byte 1)
        ldr     r2, =__mul32.frame+10  ; r2 = b (byte 2)
        ldr     r3, =__mul32.frame+11  ; r3 = b (byte 3)
        eor     r0, r0, #0             ; byte 0: 0 where b and 0 agree
        eor     r1, r1, #0             ; byte 1: 0 where b and 0 agree
        eor     r2, r2, #0             ; byte 2: 0 where b and 0 agree
        eor     r3, r3, #0             ; byte 3: 0 where b and 0 agree
        or      r0, r0, r1             ; collect the differences
        or      r0, r0, r2             ; collect the differences
        ord     r0, r3                 ; Z = all bytes equal
        br.eq   =__mul32.4             ; if b eq 0
        br      =__mul32.5             ; otherwise
__mul32.4:                              ; then: b eq 0
        br      =__mul32.3             ; break
        br      =__mul32.6             ; skip the else part
__mul32.5:                              ; not: b eq 0
__mul32.6:                              ; end of if
        ldr     r0, =__mul32.frame+8   ; r0 = b (byte 0)
        ldr     r1, =__mul32.frame+9   ; r1 = b (byte 1)
        ldr     r2, =__mul32.frame+10  ; r2 = b (byte 2)
        ldr     r3, =__mul32.frame+11  ; r3 = b (byte 3)
        and     r0, r0, #1             ; b & 1 (byte 0)
        and     r1, r1, #0             ; b & 1 (byte 1)
        and     r2, r2, #0             ; b & 1 (byte 2)
        and     r3, r3, #0             ; b & 1 (byte 3)
        eor     r0, r0, #0             ; byte 0: 0 where b & 1 and 0 agree
        eor     r1, r1, #0             ; byte 1: 0 where b & 1 and 0 agree
        eor     r2, r2, #0             ; byte 2: 0 where b & 1 and 0 agree
        eor     r3, r3, #0             ; byte 3: 0 where b & 1 and 0 agree
        or      r0, r0, r1             ; collect the differences
        or      r0, r0, r2             ; collect the differences
        ord     r0, r3                 ; Z = all bytes equal
        br.ne   =__mul32.7             ; if (b & 1) ne 0
        br      =__mul32.8             ; otherwise
__mul32.7:                              ; then: (b & 1) ne 0
        ldr     r0, =__mul32.frame+14  ; r0 = r (byte 0)
        ldr     r1, =__mul32.frame+15  ; r1 = r (byte 1)
        ldr     r2, =__mul32.frame+16  ; r2 = r (byte 2)
        ldr     r3, =__mul32.frame+17  ; r3 = r (byte 3)
        ldr     r4, =__mul32.frame+4   ; r4 = a (byte 0)
        ldr     r5, =__mul32.frame+5   ; r5 = a (byte 1)
        ldr     r6, =__mul32.frame+6   ; r6 = a (byte 2)
        ldr     r7, =__mul32.frame+7   ; r7 = a (byte 3)
        adds    r0, r0, r4             ; r + a, byte 0
        addcs   r1, r1, r5             ; ... byte 1 with carry
        addcs   r2, r2, r6             ; ... byte 2 with carry
        addc    r3, r3, r7             ; ... byte 3 with carry
        str     r0, =__mul32.frame+14  ; r (byte 0) = r0
        str     r1, =__mul32.frame+15  ; r (byte 1) = r1
        str     r2, =__mul32.frame+16  ; r (byte 2) = r2
        str     r3, =__mul32.frame+17  ; r (byte 3) = r3
        br      =__mul32.9             ; skip the else part
__mul32.8:                              ; not: (b & 1) ne 0
__mul32.9:                              ; end of if
        ldr     r0, =__mul32.frame+4   ; r0 = a (byte 0)
        ldr     r1, =__mul32.frame+5   ; r1 = a (byte 1)
        ldr     r2, =__mul32.frame+6   ; r2 = a (byte 2)
        ldr     r3, =__mul32.frame+7   ; r3 = a (byte 3)
        lsls    r0, r0                 ; a shl 1: step 1 of 1
        csls    r1, r1                 ; ... carry into byte 1
        csls    r2, r2                 ; ... carry into byte 2
        csl     r3, r3                 ; ... carry into byte 3
        str     r0, =__mul32.frame+4   ; a (byte 0) = r0
        str     r1, =__mul32.frame+5   ; a (byte 1) = r1
        str     r2, =__mul32.frame+6   ; a (byte 2) = r2
        str     r3, =__mul32.frame+7   ; a (byte 3) = r3
        ldr     r0, =__mul32.frame+8   ; r0 = b (byte 0)
        ldr     r1, =__mul32.frame+9   ; r1 = b (byte 1)
        ldr     r2, =__mul32.frame+10  ; r2 = b (byte 2)
        ldr     r3, =__mul32.frame+11  ; r3 = b (byte 3)
        lsrs    r3, r3                 ; b shr 1: step 1 of 1
        csrs    r2, r2                 ; ... carry into byte 2
        csrs    r1, r1                 ; ... carry into byte 1
        csr     r0, r0                 ; ... carry into byte 0
        str     r0, =__mul32.frame+8   ; b (byte 0) = r0
        str     r1, =__mul32.frame+9   ; b (byte 1) = r1
        str     r2, =__mul32.frame+10  ; b (byte 2) = r2
        str     r3, =__mul32.frame+11  ; b (byte 3) = r3
        br      =__mul32.2             ; again
__mul32.3:                              ; end of loop
        ldr     r0, =__mul32.frame+14  ; r0 = r (byte 0)
        ldr     r1, =__mul32.frame+15  ; r1 = r (byte 1)
        ldr     r2, =__mul32.frame+16  ; r2 = r (byte 2)
        ldr     r3, =__mul32.frame+17  ; r3 = r (byte 3)
        str     r0, =__mul32.frame     ; result (byte 0) = r0
        str     r1, =__mul32.frame+1   ; result (byte 1) = r1
        str     r2, =__mul32.frame+2   ; result (byte 2) = r2
        str     r3, =__mul32.frame+3   ; result (byte 3) = r3
        br      =__mul32.1             ; return
__mul32.1:                              ; return
        ldr     r12, =__mul32.frame+12 ; reload the return address
        ldr     r13, =__mul32.frame+13
        br      r12a                   ; back to the caller

        .data
out:
        .byte 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
        .byte 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
        .byte 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
        .byte 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
tp:
        .addr =through

        .bss

; frame of start, 24 bytes (ABI 0.3: the caller writes the arguments here)
;   +0    2   saved return address (r12a)
;   +2    2   spill slot
;   +4    2   spill slot
;   +6    1   spill slot
;   +7    4   r
;   +11   4   scratch: argument {...}
;   +15   4   scratch: argument {...}
;   +19   4   scratch: result of pswap({...}, {...}, 5)
;   +23   1   cnt
start.frame:
        .res 24

; frame of __mul16, 10 bytes (ABI 0.3: the caller writes the arguments here)
;   +0    2   result
;   +2    2   a
;   +4    2   b
;   +6    2   saved return address (r12a)
;   +8    2   r
__mul16.frame:
        .res 10

; frame of __mul32, 18 bytes (ABI 0.3: the caller writes the arguments here)
;   +0    4   result
;   +4    4   a
;   +8    4   b
;   +12   2   saved return address (r12a)
;   +14   4   r
__mul32.frame:
        .res 18
