/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 30
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_memory = 2,
  anon_sym_start = 3,
  anon_sym_size = 4,
  anon_sym_place = 5,
  anon_sym_end = 6,
  anon_sym_code = 7,
  anon_sym_data = 8,
  anon_sym_bss = 9,
  anon_sym_STAR = 10,
  anon_sym_align = 11,
  anon_sym_symbol = 12,
  anon_sym_EQ = 13,
  anon_sym_last = 14,
  sym_number = 15,
  sym_comment = 16,
  sym_source_file = 17,
  sym_memory = 18,
  sym_place = 19,
  sym_section = 20,
  sym_align = 21,
  sym_symbol_here = 22,
  sym_symbol_definition = 23,
  aux_sym_source_file_repeat1 = 24,
  aux_sym_place_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_memory] = "memory",
  [anon_sym_start] = "start",
  [anon_sym_size] = "size",
  [anon_sym_place] = "place",
  [anon_sym_end] = "end",
  [anon_sym_code] = "code",
  [anon_sym_data] = "data",
  [anon_sym_bss] = "bss",
  [anon_sym_STAR] = "*",
  [anon_sym_align] = "align",
  [anon_sym_symbol] = "symbol",
  [anon_sym_EQ] = "=",
  [anon_sym_last] = "last",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_memory] = "memory",
  [sym_place] = "place",
  [sym_section] = "section",
  [sym_align] = "align",
  [sym_symbol_here] = "symbol_here",
  [sym_symbol_definition] = "symbol_definition",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_place_repeat1] = "place_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_memory] = anon_sym_memory,
  [anon_sym_start] = anon_sym_start,
  [anon_sym_size] = anon_sym_size,
  [anon_sym_place] = anon_sym_place,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_code] = anon_sym_code,
  [anon_sym_data] = anon_sym_data,
  [anon_sym_bss] = anon_sym_bss,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_align] = anon_sym_align,
  [anon_sym_symbol] = anon_sym_symbol,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_last] = anon_sym_last,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_memory] = sym_memory,
  [sym_place] = sym_place,
  [sym_section] = sym_section,
  [sym_align] = sym_align,
  [sym_symbol_here] = sym_symbol_here,
  [sym_symbol_definition] = sym_symbol_definition,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_place_repeat1] = aux_sym_place_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_memory] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_start] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_size] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_place] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_code] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_data] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bss] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_align] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_symbol] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_last] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_memory] = {
    .visible = true,
    .named = true,
  },
  [sym_place] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_align] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol_here] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol_definition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_place_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_region = 2,
  field_size = 3,
  field_start = 4,
  field_type = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_region] = "region",
  [field_size] = "size",
  [field_start] = "start",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_region, 1},
  [1] =
    {field_type, 0},
  [2] =
    {field_name, 1},
    {field_type, 0},
  [4] =
    {field_name, 1},
  [5] =
    {field_name, 1},
    {field_region, 4},
  [7] =
    {field_name, 1},
    {field_size, 5},
    {field_start, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '0') ADVANCE(6);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '=') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(7);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(1);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'l', 6,
        'm', 7,
        'p', 8,
        's', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(18);
      if (lookahead == 't') ADVANCE(19);
      if (lookahead == 'y') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(25);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(26);
      END_STATE();
    case 16:
      if (lookahead == 'm') ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'z') ADVANCE(29);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'g') ADVANCE(32);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_bss);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 28:
      if (lookahead == 'c') ADVANCE(37);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 31:
      if (lookahead == 'b') ADVANCE(40);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_code);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_data);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_last);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_size);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 40:
      if (lookahead == 'o') ADVANCE(45);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_align);
      END_STATE();
    case 42:
      if (lookahead == 'y') ADVANCE(46);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_place);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_start);
      END_STATE();
    case 45:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_memory);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_symbol);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_memory] = ACTIONS(1),
    [anon_sym_start] = ACTIONS(1),
    [anon_sym_size] = ACTIONS(1),
    [anon_sym_place] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_code] = ACTIONS(1),
    [anon_sym_data] = ACTIONS(1),
    [anon_sym_bss] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_align] = ACTIONS(1),
    [anon_sym_symbol] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_last] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(21),
    [sym_memory] = STATE(6),
    [sym_place] = STATE(6),
    [sym_symbol_definition] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_memory] = ACTIONS(7),
    [anon_sym_place] = ACTIONS(9),
    [anon_sym_symbol] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_end,
    ACTIONS(17), 1,
      anon_sym_align,
    ACTIONS(19), 1,
      anon_sym_symbol,
    ACTIONS(15), 3,
      anon_sym_code,
      anon_sym_data,
      anon_sym_bss,
    STATE(3), 4,
      sym_section,
      sym_align,
      sym_symbol_here,
      aux_sym_place_repeat1,
  [24] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_align,
    ACTIONS(19), 1,
      anon_sym_symbol,
    ACTIONS(21), 1,
      anon_sym_end,
    ACTIONS(15), 3,
      anon_sym_code,
      anon_sym_data,
      anon_sym_bss,
    STATE(4), 4,
      sym_section,
      sym_align,
      sym_symbol_here,
      aux_sym_place_repeat1,
  [48] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_end,
    ACTIONS(28), 1,
      anon_sym_align,
    ACTIONS(31), 1,
      anon_sym_symbol,
    ACTIONS(25), 3,
      anon_sym_code,
      anon_sym_data,
      anon_sym_bss,
    STATE(4), 4,
      sym_section,
      sym_align,
      sym_symbol_here,
      aux_sym_place_repeat1,
  [72] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(36), 1,
      anon_sym_memory,
    ACTIONS(39), 1,
      anon_sym_place,
    ACTIONS(42), 1,
      anon_sym_symbol,
    STATE(5), 4,
      sym_memory,
      sym_place,
      sym_symbol_definition,
      aux_sym_source_file_repeat1,
  [94] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_memory,
    ACTIONS(9), 1,
      anon_sym_place,
    ACTIONS(11), 1,
      anon_sym_symbol,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    STATE(5), 4,
      sym_memory,
      sym_place,
      sym_symbol_definition,
      aux_sym_source_file_repeat1,
  [116] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      sym_identifier,
    ACTIONS(51), 1,
      anon_sym_STAR,
    ACTIONS(49), 6,
      anon_sym_end,
      anon_sym_code,
      anon_sym_data,
      anon_sym_bss,
      anon_sym_align,
      anon_sym_symbol,
  [134] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 6,
      anon_sym_end,
      anon_sym_code,
      anon_sym_data,
      anon_sym_bss,
      anon_sym_align,
      anon_sym_symbol,
  [146] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 6,
      anon_sym_end,
      anon_sym_code,
      anon_sym_data,
      anon_sym_bss,
      anon_sym_align,
      anon_sym_symbol,
  [158] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 6,
      anon_sym_end,
      anon_sym_code,
      anon_sym_data,
      anon_sym_bss,
      anon_sym_align,
      anon_sym_symbol,
  [170] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 6,
      anon_sym_end,
      anon_sym_code,
      anon_sym_data,
      anon_sym_bss,
      anon_sym_align,
      anon_sym_symbol,
  [182] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 4,
      ts_builtin_sym_end,
      anon_sym_memory,
      anon_sym_place,
      anon_sym_symbol,
  [192] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 4,
      ts_builtin_sym_end,
      anon_sym_memory,
      anon_sym_place,
      anon_sym_symbol,
  [202] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 4,
      ts_builtin_sym_end,
      anon_sym_memory,
      anon_sym_place,
      anon_sym_symbol,
  [212] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 4,
      ts_builtin_sym_end,
      anon_sym_memory,
      anon_sym_place,
      anon_sym_symbol,
  [222] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 4,
      ts_builtin_sym_end,
      anon_sym_memory,
      anon_sym_place,
      anon_sym_symbol,
  [232] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_number,
    ACTIONS(71), 2,
      anon_sym_start,
      anon_sym_last,
  [243] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      sym_identifier,
  [250] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym_identifier,
  [257] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym_identifier,
  [264] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
  [271] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_EQ,
  [278] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_start,
  [285] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      sym_number,
  [292] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_number,
  [299] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_size,
  [306] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      sym_identifier,
  [313] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym_identifier,
  [320] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      sym_number,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 24,
  [SMALL_STATE(4)] = 48,
  [SMALL_STATE(5)] = 72,
  [SMALL_STATE(6)] = 94,
  [SMALL_STATE(7)] = 116,
  [SMALL_STATE(8)] = 134,
  [SMALL_STATE(9)] = 146,
  [SMALL_STATE(10)] = 158,
  [SMALL_STATE(11)] = 170,
  [SMALL_STATE(12)] = 182,
  [SMALL_STATE(13)] = 192,
  [SMALL_STATE(14)] = 202,
  [SMALL_STATE(15)] = 212,
  [SMALL_STATE(16)] = 222,
  [SMALL_STATE(17)] = 232,
  [SMALL_STATE(18)] = 243,
  [SMALL_STATE(19)] = 250,
  [SMALL_STATE(20)] = 257,
  [SMALL_STATE(21)] = 264,
  [SMALL_STATE(22)] = 271,
  [SMALL_STATE(23)] = 278,
  [SMALL_STATE(24)] = 285,
  [SMALL_STATE(25)] = 292,
  [SMALL_STATE(26)] = 299,
  [SMALL_STATE(27)] = 306,
  [SMALL_STATE(28)] = 313,
  [SMALL_STATE(29)] = 320,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_place_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_place_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_place_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_place_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 1, 0, 2),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 2),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol_here, 2, 0, 4),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_align, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 3),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_place, 3, 0, 1),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol_definition, 4, 0, 4),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_place, 4, 0, 1),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol_definition, 5, 0, 5),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_memory, 6, 0, 6),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [81] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sra8ld(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
