; generated by ylangc 0.4.1 (ABI 0.4, docs/ylangc.md)

        .import uart_getc
        .import uart_getc.frame
        .import uart_putc
        .import uart_putc.frame
        .import __stack_top
        .import __bss_start
        .import __bss_end
        .export print
        .export print.frame
        .export echo
        .export echo.frame

; start-up code at address 0: set the stack pointer, zero .bss, run the @main function, stop
        .code vector
        .export _start
_start: mova    r14a, =__stack_top     ; SP = the last byte of RAM; the stack grows down
        mova    r2a, =__bss_start      ; zero .bss (all files): r2a = the next byte ...
        mova    r4a, =__bss_end        ; ... up to r4a
        mov     r0, #0
.l zero:
        cmp     r2, r4                 ; r2a - r4a
        subcd   r3, r5
        br.geu  .f =zeroed             ; reached the end
        sti     r0, r2a, #1            ; zero a byte, r2a + 1
        br      .b =zero
.l zeroed:
        brl     r12a, =echo               ; call echo
.l spin:
        br      .b =spin               ; echo returned: stop here

        .code

; ------------------------------------------------------------------------------
; print: fn([*]uint8)
; ------------------------------------------------------------------------------
        .addr   =print.frame           ; header: the frame of print ...
        .dword  6                      ; ... and its size
print:
        str     r12, =print.frame+2    ; save the return address
        str     r13, =print.frame+3
; line 7: var i: uint16 = 0;
        mov     r0, #0                 ; r0 = 0 (byte 0)
        mov     r1, #0                 ; r1 = 0 (byte 1)
        str     r0, =print.frame+4     ; i (byte 0) = r0
        str     r1, =print.frame+5     ; i (byte 1) = r1
; line 8: loop {
print.2:                                ; loop
; line 9: if (s[i] eq 0) { break; }
        ldr     r0, =print.frame+4     ; r0 = i (byte 0)
        ldr     r1, =print.frame+5     ; r1 = i (byte 1)
        ldr     r10, =print.frame      ; r10a = s
        ldr     r11, =print.frame+1
        ldo     r2, r10a, r0a          ; r2 = s[i]
        cmp     r2, #0                 ; flags = s[i] - 0
        br.eq   =print.3               ; if s[i] eq 0
; line 9: if (s[i] eq 0) { break; }
; line 10: uart_putc(s[i]);
        ldr     r0, =print.frame+4     ; r0 = i (byte 0)
        ldr     r1, =print.frame+5     ; r1 = i (byte 1)
        ldr     r10, =print.frame      ; r10a = s
        ldr     r11, =print.frame+1
        ldo     r2, r10a, r0a          ; r2 = s[i]
        str     r2, =uart_putc.frame   ; argument 1 of uart_putc = r2
        brl     r12a, =uart_putc       ; call uart_putc(s[i])
; line 11: i += 1;
        ldr     r0, =print.frame+4     ; r0 = i (byte 0)
        ldr     r1, =print.frame+5     ; r1 = i (byte 1)
        adds    r0, r0, #1             ; i + 1, byte 0
        addc    r1, r1, #0             ; ... byte 1 with carry
        str     r0, =print.frame+4     ; i (byte 0) = r0
        str     r1, =print.frame+5     ; i (byte 1) = r1
        br      =print.2               ; again
print.3:                                ; end of loop
        ldr     r12, =print.frame+2    ; reload the return address
        ldr     r13, =print.frame+3
        br      r12a                   ; back to the caller

        .code

; ------------------------------------------------------------------------------
; echo: fn()
; ------------------------------------------------------------------------------
        .addr   =echo.frame            ; header: the frame of echo ...
        .dword  3                      ; ... and its size
echo:
        str     r12, =echo.frame       ; save the return address
        str     r13, =echo.frame+1
; line 17: print(s"Y says hello\r\n");
        mova    r10a, =str.1           ; r10a = address of s"Y says hello.."
        mov     r0, r10
        mov     r1, r11
        str     r0, =print.frame       ; argument 1 of print (byte 0) = r0
        str     r1, =print.frame+1     ; argument 1 of print (byte 1) = r1
        brl     r12a, =print           ; call print(s"Y says hello..")
; line 18: loop {
echo.2:                                 ; loop
; line 19: var c: char = uart_getc();
        brl     r12a, =uart_getc       ; call uart_getc()
        ldr     r0, =uart_getc.frame   ; r0 = result of uart_getc
        str     r0, =echo.frame+2      ; c = r0
; line 20: if (c eq '\r') {
        ldr     r0, =echo.frame+2      ; r0 = c
        cmp     r0, #13                ; flags = c - 13
        br.ne   =echo.5                ; otherwise
; line 21: print(s"\r\n");
        mova    r10a, =str.2           ; r10a = address of s".."
        mov     r0, r10
        mov     r1, r11
        str     r0, =print.frame       ; argument 1 of print (byte 0) = r0
        str     r1, =print.frame+1     ; argument 1 of print (byte 1) = r1
        brl     r12a, =print           ; call print(s"..")
        br      =echo.2                ; skip the else part
echo.5:                                 ; else
; line 23: uart_putc(c);
        ldr     r0, =echo.frame+2      ; r0 = c
        str     r0, =uart_putc.frame   ; argument 1 of uart_putc = r0
        brl     r12a, =uart_putc       ; call uart_putc(c)
        br      =echo.2                ; again

        .data
str.1:
        .byte 89, 32, 115, 97, 121, 115, 32, 104, 101, 108, 108, 111, 13, 10, 0
str.2:
        .byte 13, 10, 0

        .bss

; frame of print, 6 bytes (ABI 0.4: the caller writes the arguments here)
;   +0    2   s
;   +2    2   saved return address (r12a)
;   +4    2   i
print.frame:
        .res 6

; frame of echo, 3 bytes (ABI 0.4: the caller writes the arguments here)
;   +0    2   saved return address (r12a)
;   +2    1   c
echo.frame:
        .res 3
