; generated by ylangc 0.1

        .import uart_getc
        .import uart_putc
        .import __stack_top
        .export print
        .export echo

; start-up: the stack pointer, then the @main function (ABI 0.1)
        .code vector
        .export _start
_start: mova    r14a, =__stack_top
        brl     r12a, =echo
.l spin:
        br      .b =spin

        .code

; print: fn([*]uint8)
print:
        subs    r14, r14, #4
        subc    r15, r15, #0
        adds    r10, r14, #3
        addc    r11, r15, #0
        str     r12, r10a
        adds    r10, r14, #4
        addc    r11, r15, #0
        str     r13, r10a
; 7: var i: uint16 = 0;
        mov     r0, #0
        mov     r1, #0
        adds    r10, r14, #1
        addc    r11, r15, #0
        str     r0, r10a
        adds    r10, r14, #2
        addc    r11, r15, #0
        str     r1, r10a
; 8: loop {
print.2:
; 9: if (s[i] eq 0) { break; }
        adds    r10, r14, #5
        addc    r11, r15, #0
        ldr     r0, r10a
        adds    r10, r14, #6
        addc    r11, r15, #0
        ldr     r1, r10a
        adds    r10, r14, #1
        addc    r11, r15, #0
        ldr     r2, r10a
        adds    r10, r14, #2
        addc    r11, r15, #0
        ldr     r3, r10a
        adds    r0, r0, r2
        addc    r1, r1, r3
        mov     r10, r0
        mov     r11, r1
        ldr     r2, r10a
        cmp     r2, #0
        br.eq   =print.4
        br      =print.5
print.4:
; 9: if (s[i] eq 0) { break; }
        br      =print.3
        br      =print.6
print.5:
print.6:
; 10: uart_putc(s[i]);
        subs    r14, r14, #1
        subc    r15, r15, #0
        adds    r10, r14, #6
        addc    r11, r15, #0
        ldr     r0, r10a
        adds    r10, r14, #7
        addc    r11, r15, #0
        ldr     r1, r10a
        adds    r10, r14, #2
        addc    r11, r15, #0
        ldr     r2, r10a
        adds    r10, r14, #3
        addc    r11, r15, #0
        ldr     r3, r10a
        adds    r0, r0, r2
        addc    r1, r1, r3
        mov     r10, r0
        mov     r11, r1
        ldr     r2, r10a
        adds    r10, r14, #1
        addc    r11, r15, #0
        str     r2, r10a
        brl     r12a, =uart_putc
        adds    r14, r14, #1
        addc    r15, r15, #0
; 11: i += 1;
        adds    r10, r14, #1
        addc    r11, r15, #0
        ldr     r0, r10a
        adds    r10, r14, #2
        addc    r11, r15, #0
        ldr     r1, r10a
        adds    r0, r0, #1
        addc    r1, r1, #0
        adds    r10, r14, #1
        addc    r11, r15, #0
        str     r0, r10a
        adds    r10, r14, #2
        addc    r11, r15, #0
        str     r1, r10a
        br      =print.2
print.3:
print.1:
        adds    r10, r14, #3
        addc    r11, r15, #0
        ldr     r12, r10a
        adds    r10, r14, #4
        addc    r11, r15, #0
        ldr     r13, r10a
        adds    r14, r14, #4
        addc    r15, r15, #0
        br      r12a

        .code

; echo: fn()
echo:
        subs    r14, r14, #3
        subc    r15, r15, #0
        adds    r10, r14, #2
        addc    r11, r15, #0
        str     r12, r10a
        adds    r10, r14, #3
        addc    r11, r15, #0
        str     r13, r10a
; 17: print(s"Y says hello\r\n");
        subs    r14, r14, #2
        subc    r15, r15, #0
        mova    r10a, =str.1
        mov     r0, r10
        mov     r1, r11
        adds    r10, r14, #1
        addc    r11, r15, #0
        str     r0, r10a
        adds    r10, r14, #2
        addc    r11, r15, #0
        str     r1, r10a
        brl     r12a, =print
        adds    r14, r14, #2
        addc    r15, r15, #0
; 18: loop {
echo.2:
; 19: var c: char = uart_getc();
        subs    r14, r14, #1
        subc    r15, r15, #0
        brl     r12a, =uart_getc
        adds    r10, r14, #1
        addc    r11, r15, #0
        ldr     r0, r10a
        adds    r14, r14, #1
        addc    r15, r15, #0
        adds    r10, r14, #1
        addc    r11, r15, #0
        str     r0, r10a
; 20: if (c eq '\r') {
        adds    r10, r14, #1
        addc    r11, r15, #0
        ldr     r0, r10a
        cmp     r0, #13
        br.eq   =echo.4
        br      =echo.5
echo.4:
; 21: print(s"\r\n");
        subs    r14, r14, #2
        subc    r15, r15, #0
        mova    r10a, =str.2
        mov     r0, r10
        mov     r1, r11
        adds    r10, r14, #1
        addc    r11, r15, #0
        str     r0, r10a
        adds    r10, r14, #2
        addc    r11, r15, #0
        str     r1, r10a
        brl     r12a, =print
        adds    r14, r14, #2
        addc    r15, r15, #0
        br      =echo.6
echo.5:
; 23: uart_putc(c);
        subs    r14, r14, #1
        subc    r15, r15, #0
        adds    r10, r14, #2
        addc    r11, r15, #0
        ldr     r0, r10a
        adds    r10, r14, #1
        addc    r11, r15, #0
        str     r0, r10a
        brl     r12a, =uart_putc
        adds    r14, r14, #1
        addc    r15, r15, #0
echo.6:
        br      =echo.2
echo.3:
echo.1:
        adds    r10, r14, #2
        addc    r11, r15, #0
        ldr     r12, r10a
        adds    r10, r14, #3
        addc    r11, r15, #0
        ldr     r13, r10a
        adds    r14, r14, #3
        addc    r15, r15, #0
        br      r12a

        .data
str.1:
        .byte 89, 32, 115, 97, 121, 115, 32, 104, 101, 108, 108, 111, 13, 10, 0
str.2:
        .byte 13, 10, 0
